INSERT INTO RESENHAS ( res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao)VALUES
(3,5,'Harry Potter e a Pedra Filosofal','Harry Potter e a Pedra Filosofal, escrito por J.K. Rowling, é o primeiro livro da icônica série que conquistou leitores de todas as idades ao redor do mundo. Publicado originalmente em 1997, a obra apresenta um universo mágico fascinante e um protagonista cativante, embarcando em uma jornada de autodescoberta e aventura.A história acompanha Harry Potter, um garoto órfão que vive uma vida miserável na casa de seus tios, os Dursley. Tudo muda quando ele descobre, no dia do seu aniversário de 11 anos, que na verdade é um bruxo e foi aceito na Escola de Magia e Bruxaria de Hogwarts. Lá, ele faz amigos inesquecíveis, como Rony Weasley e Hermione Granger, e inimigos perigosos, como Draco Malfoy e o professor Snape.Ao longo do ano letivo, Harry aprende sobre seu passado e sobre o terrível bruxo Lorde Voldemort, responsável pela morte de seus pais. Ele também se envolve em um mistério relacionado à Pedra Filosofal, um artefato mágico capaz de conceder imortalidade. Junto com seus amigos, Harry enfrenta desafios e desvenda segredos que o levam a um confronto decisivo com as forças do mal.O livro se destaca pelo universo bem construído, personagens carismáticos e uma narrativa envolvente. J.K. Rowling mistura fantasia, mistério e humor de forma magistral, criando uma história acessível tanto para crianças quanto para adultos.No geral, Harry Potter e a Pedra Filosofal é uma introdução brilhante ao mundo mágico da série. Com uma trama instigante e mensagens sobre amizade, coragem e o poder do bem contra o mal, a obra se tornou um clássico da literatura infantojuvenil e segue encantando gerações de leitores.','0',5);

INSERT INTO RESENHAS ( res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao)VALUES
(3, 5, 'Harry Potter e a Câmara Secreta', 'Após seu primeiro ano em Hogwarts, Harry Potter esperava ansiosamente pelo retorno à escola de magia. No entanto, suas férias na casa dos tios Dursley foram ainda mais insuportáveis do que o normal, e para piorar, um visitante inesperado aparece em seu quarto: Dobby, um elfo doméstico que o avisa de um grande perigo à sua espera em Hogwarts e insiste para que ele não volte. Apesar dos avisos, Harry, com a ajuda de Rony Weasley e um carro voador encantado, consegue retornar à escola. Mas logo ele percebe que algo realmente estranho está acontecendo. Mensagens misteriosas aparecem nas paredes dos corredores, anunciando que a Câmara Secreta foi reaberta e que o herdeiro de Salazar Sonserina libertou um monstro para atacar os alunos que não são de sangue puro. Vários estudantes acabam petrificados, e o medo toma conta de Hogwarts. Enquanto isso, Harry começa a ouvir uma voz ameaçadora pelos corredores, algo que ninguém mais parece perceber. Determinados a descobrir o que está acontecendo, Harry, Rony e Hermione mergulham em uma investigação perigosa para encontrar o responsável pelos ataques.
Durante sua busca, eles descobrem um diário antigo que pertenceu a um aluno chamado Tom Riddle, que viveu em Hogwarts 50 anos antes. Através das memórias guardadas no diário, Harry descobre que Hagrid foi acusado, no passado, de abrir a Câmara Secreta e libertar o monstro. No entanto, as pistas indicam que a verdade pode ser bem diferente. Conforme o mistério se aprofunda, Harry percebe que seu próprio passado pode estar mais ligado a essa história do que ele imaginava, e que enfrentar esse inimigo será um desafio muito maior do que ele esperava.
Esse segundo livro da saga Harry Potter traz um tom mais sombrio e misterioso, aprofundando a mitologia do mundo bruxo e apresentando personagens marcantes. Dobby, o elfo doméstico, é um dos destaques da história, trazendo tanto momentos engraçados quanto emocionantes. Gilderoy Lockhart, o novo professor de Defesa Contra as Artes das Trevas, se mostra um charlatão vaidoso e sem talento, garantindo momentos de humor. Enquanto isso, a amizade entre Harry, Rony e Hermione se fortalece ainda mais, com cada um desempenhando um papel essencial na resolução do mistério.
Além de ser uma aventura mágica envolvente, Harry Potter e a Câmara Secreta aborda temas mais profundos, como preconceito e exclusão. A ideia da "pureza de sangue" e a discriminação contra bruxos de origem trouxa são elementos centrais da trama, tornando a história ainda mais relevante e impactante. A narrativa de J.K. Rowling continua envolvente e detalhada, com uma trama bem construída e repleta de reviravoltas que mantêm o leitor preso até a última página.
Com muito mistério, humor e cenas eletrizantes, Harry Potter e a Câmara Secreta é uma continuação brilhante da série, ampliando o universo de Hogwarts e preparando o terreno para desafios ainda maiores. Mais do que apenas uma história de magia, este livro explora coragem, lealdade e o poder das escolhas, provando mais uma vez por que a saga Harry Potter se tornou um dos maiores fenômenos da literatura.', 0, 5);

INSERT INTO RESENHAS ( res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao)VALUES
(3 ,6 ,'Harry Potter e o Prisioneiro de Azkaban', 'Harry Potter e o Prisioneiro de Azkaban é o terceiro livro da série escrita por J.K. Rowling, lançado originalmente em 1999. Nele, o universo mágico se expande de maneiras significativas, aprofundando os mistérios e as relações entre os personagens. A obra mistura elementos de mistério, aventura e drama com uma atmosfera sombria, que se distancia um pouco do tom mais leve e infantil dos dois primeiros livros da saga, preparando o terreno para eventos mais complexos que se seguirão.
O livro começa com Harry Potter em suas férias de verão, mais uma vez com os tios e a prima, que o tratam mal. A tensão familiar é palpável, e o autor nos coloca mais uma vez na situação desconfortável de Harry com seus parentes, especialmente após o sucesso de suas aventuras nos dois primeiros anos na Escola de Magia e Bruxaria de Hogwarts. Porém, o enredo toma um rumo dramático quando Harry escapa de casa após um incidente em que sua prima, Dudley, e seus amigos fazem de tudo para provocá-lo. Este momento de fuga marca o início de uma jornada de autodescoberta e revelações.
Ao chegar ao terceiro ano de Hogwarts, Harry se depara com uma nova ameaça: o prisioneiro de Azkaban, Sirius Black, teria fugido da prisão mais temida do mundo bruxo, e agora estaria à solta, em busca de Harry. A fuga de Sirius Black cria um clima de incerteza e medo dentro da escola, principalmente porque a história por trás de sua prisão está envolta em mistérios. Por ser considerado um traidor que teria entregado os pais de Harry, Lily e James Potter, à Voldemort, Black é visto como um dos mais perigosos criminosos da história recente do mundo bruxo. Sua fuga acirra ainda mais os ânimos em Hogwarts, e, enquanto Harry tenta entender o que realmente aconteceu, ele vai se deparando com verdades que desafiarão suas crenças sobre o passado.
A narrativa explora com profundidade a relação de Harry com seus amigos, Ron Weasley e Hermione Granger, além de trazer novas e interessantes figuras ao enredo, como o professor Lupin, que se torna professor de Defesa Contra as Artes das Trevas. Lupin se destaca por sua abordagem empática e eficaz no ensino, e sua história pessoal, revelada mais tarde, é uma das muitas camadas que enriquecem o livro. A chegada de Sirius Black como o grande mistério que paira sobre a história é acompanhada pela figura de Remus Lupin, que logo se mostra um personagem essencial na vida de Harry.
Além disso, o livro aprofunda o conceito de lealdade e traição, algo que se reflete em várias relações dentro do enredo. A busca por respostas sobre a verdadeira identidade de Sirius Black e a descoberta de sua ligação com os pais de Harry, assim como a revelação de quem realmente traiu os Potter, são momentos chave da narrativa. O suspense e a complexidade da trama se entrelaçam com o desenvolvimento emocional dos personagens, fazendo com que o leitor também questione o que é real e o que não é, enquanto o próprio Harry tenta entender seu lugar no mundo e sua conexão com os eventos passados.
O livro também explora o conceito de amizade, mostrando a força das relações que Harry estabelece ao longo de sua jornada. A amizade de Harry, Ron e Hermione se fortalece diante das adversidades, mas também se coloca à prova, especialmente no momento em que os amigos começam a descobrir segredos dolorosos sobre as famílias de cada um. A lealdade entre os três personagens principais é um dos pilares da obra e é testada à medida que enfrentam os perigos de Azkaban, a caça a Sirius Black e o mistério envolvendo o mapa do maroto.
Um dos elementos mais fascinantes do livro é o uso do "Tempo" como recurso narrativo. A introdução do vira-tempo, um objeto mágico que permite viajar no tempo, cria uma série de situações onde Harry e Hermione precisam revisitar momentos do passado, alterando eventos para salvar vidas e corrigir injustiças. Esse recurso, além de ser um elemento de fantasia, também toca em questões filosóficas sobre o que seria possível mudar se tivéssemos o poder de voltar no tempo.
A construção do cenário em "O Prisioneiro de Azkaban" também é notável. A atmosfera de mistério e o clima de constante tensão, com as ameaças de Sirius Black e a presença da figura enigmática de Lupin, são ampliados com o detalhamento da escola e dos novos lugares visitados, como o Beco Diagonal e a Hogsmeade, que se tornam essenciais para a trama. O próprio conceito de Azkaban, com suas características sombrias e sua conexão com os Dementadores, é uma criação que se destaca pela sua singularidade e o peso emocional que carrega.
Ao longo da história, Harry não apenas descobre mais sobre seu passado, mas também sobre sua própria identidade e seu papel no combate ao mal. As revelações sobre a verdadeira natureza de Sirius Black e o fato de ele não ser um traidor mudam a percepção que Harry tem sobre si mesmo, seus pais e o legado que carrega. Este é um ponto crucial na série, pois é quando Harry começa a entender que a luta contra Voldemort não é apenas uma questão de sobrevivência, mas também de legado, escolha e sacrifício.
A obra, assim, se distancia do que seria uma simples história de magia para tratar de temas mais profundos como a amizade, o perdão, a perda e o enfrentamento das próprias inseguranças. Rowling, com maestria, consegue aliar uma narrativa envolvente a temas universais, mantendo o encantamento de um mundo mágico com o peso da realidade humana.
No fim, Harry Potter e o Prisioneiro de Azkaban se afirma como um dos livros mais emocionantes e complexos da saga, preparando o terreno para os conflitos ainda mais intensos que se seguirão nos próximos volumes. A tensão crescente, a revelação de segredos e a exploração de novos personagens fazem dessa obra uma peça fundamental para o entendimento do desenvolvimento de Harry e do mundo mágico como um todo.', 0, 3),
(3,7, 'Harry Potter  e o Calice de Fogo','Primeiro que essa sinopse nem é uma sinopse direito. Está mais para um resumo da obra porque olha... Enfim... Harry Potter e o Cálice de Fogo é um dos meus filmes favoritos e o livro não fica muito atrás.
O diferencial desse livro para os outros três é que a ação é do começo ao fim, por causa do Torneio Tribuxo. Apesar das tarefas terem sido adaptadas um pouco diferentes, as tarefas descritas no livro são de tirar o fôlego e emocionantes. Com a participação das escolas de Beauxbatons e Durmstrang expande um pouco o mundo além das paredes de Hogwarts, mostrando um pouco dos costumes e alunos das outras duas escolas importantes da Europa.
Falando em Torneio Tribuxo, ele divide espaço com as atividades escolares dos alunos. O que pareceu ter rolado em pouco tempo no filme, aqui leva-se praticamente um ano todo para que acabe o torneio. Em certos momentos, se torna um pouco maçante ver o dia-a-dia das aulas e tudo mais, algo que já fomos apresentados, mas eu entendi que era pra dar mais uma cadência na história. Como se quisesse passar a mensagem “ganhar o torneio é bom, mas estudar também é importante), já que os campeões realmente tinham de analisar e estudar uma forma de passar por todas as tarefas ilesos.
E é nesse livro que finalmente Voldemort dá as caras. A cena de sua ressurreição é bem intensa e com um ar mais sombrio, se comparada com os outros livros. Tio Voldy é um vilão que já chega mostrando que não está para brincadeira.Um detalhe que senti falta no filme foi mostrar o sr. Weasley buscando Harry na casa dos Dursleys, para acompanhar a final da Copa Mundial de Quadribol. Os urros que dei ao ler essa cena não podem ser escritos. Gêmeos Weasley seguem sendo os melhores personagens dessa série e tenho dito.Muitos fãs reclamaram sobre não adaptarem Hermione comandando a F.A.L.E (Fundo de Apoio à Liberdade dos Elfos). Até entendo que seria interessante ver a bruxa mais inteligente de Hogwarts militando a favor de direitos melhores para os elfos, mas confesso que seria uma quebra da linha da história. Assim como Rita e suas fofocas, as cenas referentes a esse assunto eram de um certo alívio cômico.Falando na repórter, Rita Skeeter e suas fofocas não têm muito foco no filme, mas no livro elas causam e arrasam muito burburinho em Hogwarts. Isso mostra que, bruxos ou não, ninguém resiste a uma boa fofoca.Em Harry Potter e o Cálice de Fogo, JK já começa a traçar alguns acontecimentos que serão bastante importantes nos próximos livros. Houveram algumas conversas na reta final que eu já fiquei bem atenta. Atenta e ansiosa para Harry Potter e A Ordem da Fênix.',0, 4);

INSERT INTO RESENHAS ( res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao)VALUES
(3,10,'Harry Potter  e as Relíquias da Morte','Finalmente, com um grande atraso, terminei minha releitura de Harry Potter. A história continua sendo maravilhosa, apesar de que tenho outra visão sobre alguns acontecimentos, mas nada que vá macular o carinho que sinto pela série.
Em As Relíquias da Morte, Harry está à caça das horcruxes a fim de derrotar Lord Voldemort. Com a ajuda de Rony e Hermione, ele sabe que essa procura não vai ser nada fácil. Ao longo dessa procura, Harry vai descobrir mais sobre o seu papel como O Menino que Sobreviveu.
Esse livro já tem um clima pesado desde seu início. Voldemort está de volta e tocando o terror em tudo e todos que sequer pensem em proteger e ajudar Harry. Apesar de ter achado que a JK enrolou um pouco naquela sequência após o casamento do Gui e da Fleur, que o trio ficam refugiados por um tempo no Largo Grimmauld, esse livro ainda é um dos meus favoritos da série.
É de se pensar que esse teria muitas cenas de ação e lutas por conta do embate com Voldemort e os Comensais da Morte. Eu achei que foram inseridas no momento certo, apesar de ter percebido que a JK não descreveu muito bem algumas. Na verdade, eu achei as descrições um tanto fracas em momento na batalha em Hogwarts.
Um dos pontos fortes do livro são as informações reveladas sobre o passado de Dumbledore. O ex-diretor de Hogwarts sempre pareceu ser um personagem com bastante segredos e nesse livro contamos com a versão bruxa de Sônia Abraão para explorar a morte do diretor, vendendo sua biografia. Um lado positivo dessa releitura foi justamente lembrar desses detalhes e ver como algumas coisas em Animais Fantásticos e Onde Eles Habitam contradizem. Vida que segue…
Entretanto se tem algo que não compro de jeito algum é a tal da redenção do Snape. Mesmo somente quando assistia os filmes (a primeira vez que li a série, iniciei quando estava saindo o sexto filme), eu sempre achei um personagem bastante abusivo com seus alunos, principalmente na questão psicológica. Então, não entra na minha cabeça um cara que é o bicho-papão de um aluno vir com essa história de redenção mixuruca no fim da história.
Quanto a Voldemort, ele sempre foi um vilão que vemos através da mente de Harry, mas ainda assim ele se tornou um dos meus vilões favoritos das séries de fantasia. Muito bem construído durante toda a saga, é um vilão que, ao mesmo tempo apela para o medo e terror em seus seguidores, ele também atinge a crueldade e maldade de alguns bruxos não-contentes com a situação de viverem escondidos.
Harry Potter e as Relíquias da Morte consegue fechar muito bem toda a saga d’O Menino que Sobreviveu, deixando aquele sentimento de dever cumprido e saudades de personagens que acompanhamos desde o início. Por isso, eu digo: JK, mana, para de ficar revelando informações desnecessárias e surreais sobre os personagens que tanto amamos, belezoca?',0, 4);

INSERT INTO RESENHAS 
(res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao)
VALUES 
(
    3, 11, 'O chamado selvagem', 
    'O Chamado Selvagem é uma das obras mais emblemáticas de Jack London, publicada em 1903. Este romance, ambientado nas regiões geladas do Yukon, no Canadá, durante a corrida do ouro do Klondike, é uma história sobre sobrevivência, adaptação e a luta pela liberdade. A narrativa acompanha a jornada de Buck, um cão domesticado que, após ser sequestrado e vendido para trabalhar como cão de trenó, vai sendo gradualmente forçado a voltar à sua essência primitiva, respondendo ao chamado selvagem que ecoa nas suas veias. London, com uma escrita crua e poética, constrói uma reflexão profunda sobre a natureza humana e animal, sobre o instinto e a civilização, e sobre como a vida selvagem, apesar de brutal, também carrega um certo tipo de pureza e verdade.

    A história começa com Buck, um grande cão mestiço de São Bernardo e collie, vivendo uma vida tranquila e confortável em uma propriedade na Califórnia, com seu dono, um homem respeitável que o trata com carinho e respeito. Porém, o destino de Buck muda radicalmente quando ele é sequestrado e levado para o norte gelado do Canadá. Ali, ele começa a enfrentar uma realidade dura e impiedosa. O cão, que até então tinha sido um animal domesticado, se vê diante de uma vida de trabalhos forçados, onde é constantemente maltratado pelos homens e obrigado a lutar pela sua sobrevivência em um ambiente implacável.

    O primeiro choque que Buck experimenta ao ser transportado para o norte é a crueldade com que os homens o tratam. Ele é submisso a uma nova realidade, onde a bondade é escassa e a luta pela sobrevivência é constante. Logo, ele é confrontado com as leis implacáveis da natureza selvagem e da hierarquia dentro do time de cães de trenó, onde cada cão tem seu lugar e onde a força física e o espírito de luta são determinantes para a sobrevivência. Buck, inicialmente incrédulo e assombrado com a brutalidade do novo mundo, começa a aprender as regras desse novo jogo, com uma intuição que o guia para sua adaptação. Ele começa a reconhecer os sinais de seus instintos primitivos e, pouco a pouco, vai se desconectando do mundo domesticado que o definia anteriormente.

    A luta de Buck para se impor no grupo de cães é uma das partes centrais do romance. Em um momento de extrema tensão, ele enfrenta Spitz, o cão dominante do time, que representa não só o líder do grupo, mas também a força bruta necessária para sobreviver naquela sociedade. Ao derrotar Spitz, Buck assume o seu lugar como o novo líder, uma conquista que simboliza sua transição da domesticidade para a selvageria. A partir daí, Buck se apropria de sua nova identidade, mais próxima de sua ancestralidade selvagem. A natureza, então, começa a ter um papel fundamental no desenvolvimento de Buck, e ele responde cada vez mais ao chamado de seu sangue, sentindo uma atração irresistível pelos elementos mais primitivos do mundo que o cerca.

    Ao longo da narrativa, a relação de Buck com os seres humanos é complexa e, por vezes, contraditória. A princípio, ele encara os homens com desconfiança, sempre esperando o pior deles. Mas, ao mesmo tempo, há momentos em que ele se apega a algumas figuras, como John Thornton, um homem que, ao contrário dos outros, demonstra bondade e respeito por Buck. A relação entre ambos é genuína e baseada na confiança mútua, representando uma espécie de redenção para Buck, que finalmente experimenta o carinho e o respeito por um ser humano. No entanto, mesmo esse vínculo é, de certa forma, incapaz de impedir que Buck continue a seguir seu instinto de voltar à natureza. Ao longo do romance, ele se vê cada vez mais afastado da civilização, mais envolto na força da natureza e mais em sintonia com seu lado animal. O chamado selvagem, que inicialmente parecia algo distante e misterioso, se torna uma realidade irresistível.

    A habilidade de Jack London em construir o mundo selvagem de maneira visceral e realista é uma das grandes qualidades do livro. Ele não só descreve a paisagem fria e implacável do Yukon, como também transmite a brutalidade da vida selvagem, onde os animais lutam pela sobrevivência e onde a morte está sempre à espreita. A luta de Buck pela sobrevivência não é apenas uma metáfora para a vida humana, mas uma representação de como os instintos primitivos podem ser mais poderosos do que qualquer civilização ou moralidade que tentemos impor.

    O final de O Chamado Selvagem é carregado de simbolismo e emoção. Buck finalmente sucumbe ao chamado da natureza. Ele segue para a floresta, onde encontra seu lugar como um líder dos lobos, e, ao fazê-lo, alcança uma paz e uma liberdade que nunca poderia encontrar no mundo dos homens. A jornada de Buck é uma metáfora poderosa para a busca por liberdade, identidade e autoconhecimento. A transição de Buck de um animal domesticado para um ser selvagem, capaz de liderar um bando de lobos, é uma jornada de transformação que ressoa com as questões fundamentais da existência: o que significa ser livre, o que significa ser quem realmente somos e como, em um mundo impiedoso, a natureza pode nos exigir uma mudança radical.

    O livro também aborda, com uma grande carga filosófica, a ideia de que, por mais que a civilização tente domesticar e controlar a natureza e os instintos, há uma força primitiva que não pode ser erradicada. A selvageria é uma parte intrínseca de Buck, e sua jornada é uma volta ao que ele sempre foi por dentro, mesmo em um corpo domesticado. É uma reflexão sobre a natureza da liberdade, do poder e da luta pela sobrevivência, que ressoam não só com os animais, mas também com os seres humanos.

    O Chamado Selvagem não é apenas uma história sobre um cão, mas uma reflexão profunda sobre a luta entre a domesticação e a selvageria, sobre a natureza humana e animal, e sobre a busca por liberdade e identidade. London, com sua habilidade de criar uma narrativa envolvente e cheia de emoção, nos oferece mais do que uma simples história de aventura; ele nos dá um retrato vívido e tocante da relação entre o homem, o animal e a natureza, e nos desafia a refletir sobre até que ponto nossas raízes selvagens ainda permanecem conosco, mesmo quando estamos imersos na civilização.', 
    0, 4
);

INSERT INTO RESENHAS  (res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao) VALUES 
(3,8,'Harry Potter e a Ordem da Fênix','Harry Potter e a Ordem da Fênix é o quinto livro da saga criada por J.K. Rowling e marca um ponto de virada na história do jovem bruxo. Com uma narrativa mais sombria e densa, a obra aprofunda os conflitos internos de Harry, suas lutas contra a opressão e a resistência contra as forças do mal. Publicado em 2003, o livro traz um desenvolvimento emocional mais complexo dos personagens, além de introduzir novos elementos à mitologia do universo mágico.A trama começa com Harry isolado e frustrado no verão, sem notícias do mundo bruxo após os acontecimentos traumáticos do Torneio Tribruxo e o retorno de Voldemort. Seu desespero cresce quando é atacado por Dementadores em Little Whinging e, ao se defender com um feitiço do Patrono, recebe uma intimação para ser julgado pelo Ministério da Magia por praticar magia fora de Hogwarts.Esse evento dá o tom do livro: um Harry mais revoltado, desconfiado e emocionalmente abalado. Ele descobre a existência da Ordem da Fênix, um grupo de resistência contra Voldemort liderado por Alvo Dumbledore, que conta com membros como Sirius Black, Remo Lupin e a recém-introduzida Ninfadora Tonks. No entanto, a ameaça não vem apenas do Lorde das Trevas, mas também do próprio Ministério da Magia, que se recusa a aceitar o retorno de Voldemort e inicia uma campanha de difamação contra Harry e Dumbledore.Esse negacionismo culmina na imposição de Dolores Umbridge como nova professora de Defesa Contra as Artes das Trevas e, posteriormente, como Alta Inquisidora de Hogwarts. Umbridge, talvez uma das personagens mais odiadas da série, simboliza a tirania e o abuso de poder, implementando uma série de regras opressivas e punições cruéis. A resistência de Harry e seus amigos leva à formação da Armada de Dumbledore, um grupo secreto que treina magia defensiva para se preparar contra as forças das trevas.O livro também explora a conexão mental cada vez mais forte entre Harry e Voldemort, mostrando como o protagonista pode involuntariamente acessar os pensamentos e emoções do vilão. Esse elo se torna fundamental para a batalha final no Departamento de Mistérios, onde a Ordem da Fênix enfrenta os Comensais da Morte e uma verdade dolorosa é revelada: a profecia que define Harry como "o único que pode derrotar o Lorde das Trevas".Além da ação e do suspense, A Ordem da Fênix aprofunda temas como repressão governamental, resistência juvenil e os desafios da adolescência. A raiva e a frustração de Harry são palpáveis, tornando-o um personagem mais humano e falho. A perda trágica de Sirius Black no final do livro adiciona um peso emocional significativo, consolidando o tom mais sombrio da saga.Com uma escrita envolvente e um enredo complexo, Harry Potter e a Ordem da Fênix é uma leitura intensa e emocionante, que amplia o universo da série e prepara o terreno para os confrontos finais contra Voldemort. É um livro sobre luta, amadurecimento e a importância de se manter firme diante da injustiça.',0, 5);

INSERT INTO RESENHAS  (res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao) VALUES 
(3, 12,'Caninos Brancos','Caninos Brancos, de Jack London, é uma obra que mergulha no espírito selvagem e nos conflitos internos de um lobo que, ao longo de sua vida, enfrenta a dura realidade da sobrevivência em ambientes implacáveis. A história começa nas vastas e inóspitas regiões do Alasca, onde Canino Branco, um filhote nascido da união de um lobo selvagem com uma cadela domesticada, cresce em um mundo cruel. Desde cedo, ele é forçado a lutar pela sobrevivência, enfrentando o frio, a fome e o perigo constante, características que o fazem desenvolver uma natureza feroz e instintiva.
A relação de Canino Branco com os humanos começa de forma extremamente hostil e marcada pela brutalidade. Ele é capturado por caçadores e, mais tarde, vendido para Gray Beaver, um nativo que o vê apenas como uma ferramenta de trabalho. O animal é tratado com dureza, sendo constantemente maltratado, o que alimenta ainda mais sua natureza desconfiada e agressiva. A interação de Canino Branco com os humanos é marcada pela desconfiança mútua e pela luta pela dominação, uma luta constante pela definição de quem deve ser o verdadeiro “dominante” na relação.
A transformação de Canino Branco começa a ocorrer quando ele é adquirido por Weedon Scott, um homem branco que se destaca pela sua bondade e compreensão. Scott, diferentemente dos outros, não vê o lobo como uma simples máquina de trabalho ou uma besta selvagem, mas como um ser complexo, capaz de aprender e até mesmo formar laços. A convivência com Weedon Scott e o tratamento respeitoso que ele oferece são cruciais para a mudança no comportamento do animal. Com o tempo, Canino Branco começa a confiar em Scott e, embora ainda carregue consigo as marcas de sua origem selvagem, ele se torna mais sociável, mais afetuoso e menos agressivo. Esse relacionamento de confiança mútua culmina no entendimento de que a verdadeira natureza de Canino Branco, apesar de sua brutalidade inicial, também inclui uma capacidade de lealdade e carinho.
O livro é uma reflexão sobre a natureza humana e animal, sobre como a convivência com os seres humanos pode tanto domesticar quanto salvar um ser selvagem. Ao longo da narrativa, London nos mostra que, embora o instinto de sobrevivência e a brutalidade estejam profundamente enraizados na natureza de Canino Branco, a bondade e o respeito também têm o poder de moldar e transformar um ser, por mais selvagem que seja. A relação entre o homem e o animal é explorada de maneira profunda, com a obra levantando questões sobre o que realmente significa ser domesticado e o que permanece de nossa essência selvagem, mesmo quando buscamos nos adaptar à sociedade humana.
A escrita de Jack London é vívida, com uma grande habilidade para capturar as paisagens desoladas do Alasca e a luta feroz pela sobrevivência, e ao mesmo tempo transmitir as emoções e os conflitos internos de Canino Branco. A natureza selvagem e impiedosa é um personagem à parte na obra, representando não apenas o cenário onde o lobo vive, mas também os desafios internos que ele enfrenta. London nos oferece uma história cheia de ação, mas também de reflexão, tornando Caninos Brancos uma leitura que explora as complexidades da vida, da lealdade, da sobrevivência e da convivência entre seres tão diferentes.
',0, 5),
(4,9,'Harry Potter  e o Enigma do Principe','"Harry Potter e o Enigma do Príncipe" é o sexto livro da série de J.K. Rowling, que continua a explorar a jornada de Harry Potter, um jovem bruxo, em um mundo cada vez mais ameaçado pelas forças das trevas. Com um tom mais sombrio e um ritmo mais lento que os volumes anteriores, a obra destaca-se pela profundidade emocional e pela complexidade dos personagens, ao mesmo tempo em que constrói uma base sólida para o confronto final com Lord Voldemort.
A história começa com Harry retornando à escola de magia de Hogwarts, agora em um período em que a guerra contra Voldemort já está em plena ebulição. O livro se concentra, sobretudo, na preparação de Harry para enfrentar os desafios que estão por vir, e, para isso, ele recebe uma ajuda crucial de um dos personagens mais misteriosos da série: o professor Horácio Slughorn. Este personagem se torna uma peça fundamental ao longo da trama, pois ele guarda lembranças essenciais para a compreensão do verdadeiro plano de Voldemort. Através dessas memórias, Harry e Dumbledore tentam descobrir como derrotar o vilão de uma vez por todas.
A relação entre Harry e Dumbledore se torna o centro emocional da narrativa, com Dumbledore desempenhando o papel de mentor e guia para o jovem bruxo. Essa dinâmica, que já era forte nos livros anteriores, ganha uma nova camada de complexidade, especialmente no momento em que Dumbledore revela mais sobre o passado de Voldemort e as Horcruxes, objetos mágicos que contêm fragmentos da alma de Voldemort. Essa revelação muda o curso da história, pois a missão de Harry se torna não apenas a de derrotar o vilão, mas também de destruir esses artefatos que garantem a imortalidade de Voldemort.
Ao mesmo tempo, o romance começa a ganhar mais destaque. O livro dedica mais espaço aos dilemas e aos sentimentos dos personagens, como o amor não correspondido de Ron e Hermione, e o relacionamento complicado entre Harry e Ginny. A jovem Weasley, em particular, ganha uma maior relevância, e sua história com Harry se desenvolve de maneira orgânica, embora também seja marcada pela tensão das circunstâncias ao redor deles. O aspecto romântico não se sobrepõe à trama central, mas adiciona um toque de humanidade aos personagens, mostrando como eles tentam encontrar algum tipo de normalidade em meio ao caos.
Rowling também é hábil em criar uma atmosfera de suspense, e há uma constante sensação de que algo muito grave está por vir. O mistério envolvendo a identidade do "Príncipe Mestiço", personagem do título, é outro ponto intrigante da obra, uma reviravolta que se revela de maneira impactante, com implicações profundas sobre a natureza dos personagens. O livro é mais introspectivo do que os anteriores, com os personagens lidando com questões pessoais e emocionais, mas sem perder de vista a grande ameaça que paira sobre eles.
O clímax do livro é uma das partes mais dramáticas e trágicas de toda a série. A morte de um personagem importante, que ocorre de maneira inesperada e brutal, deixa uma marca indelével na história e muda para sempre a trajetória de Harry e seus amigos. Essa morte, que é central para o desenvolvimento da trama, serve como um lembrete de que a guerra contra Voldemort está se intensificando e que o sacrifício é inevitável para alcançar a vitória final.
"Harry Potter e o Enigma do Príncipe" é, sem dúvida, um livro de transição, preparando o palco para o confronto final que ocorrerá em "Harry Potter e as Relíquias da Morte". Ao mesmo tempo, ele é uma obra rica em desenvolvimento de personagens e em construção de um mundo cada vez mais detalhado e complexo. Com uma narrativa envolvente, profundidade emocional e grandes revelações, o livro é uma das partes mais bem-sucedidas da série, mantendo o leitor ansioso por mais e oferecendo uma visão mais sombria e madura do universo de Harry Potter.', 0, 4);

INSERT INTO RESENHAS  (res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao) VALUES 
(5,13,'Diário de um Banana 1','"Diário de um Banana 1" é o primeiro volume da série escrita por Jeff Kinney, que tem encantado milhões de leitores ao redor do mundo com suas histórias leves e engraçadas. O livro é contado em forma de diário, com o protagonista Greg Heffley narrando sua vida cotidiana e seus pensamentos de forma irreverente, com a visão cômica de um adolescente que tenta navegar pelas dificuldades da escola e da vida familiar.
A narrativa é simples e direta, refletindo a perspectiva de um jovem de 11 anos, cujos dilemas são bastante familiares a qualquer pessoa que tenha atravessado a pré-adolescência. Greg é um garoto que não se encaixa nos padrões tradicionais de "herói" e não se preocupa em ser popular ou em agradar a todos, o que o torna um personagem facilmente relacionável, especialmente para aqueles que já passaram pela fase de inseguranças e incertezas dessa fase da vida.
Ao longo do livro, o leitor se depara com as frustrações de Greg, como a relação difícil com seu irmão mais velho, Rodrick, e o desdém que ele sente pela vida escolar, especialmente pela educação física, que ele tenta evitar de todas as formas. O protagonista é um garoto que vive tentando encontrar atalhos para o sucesso, muitas vezes com soluções que não são muito bem pensadas, o que acaba gerando situações extremamente engraçadas, mas também reveladoras de sua personalidade um tanto egoísta e preguiçosa.
Além das situações engraçadas que surgem de suas tentativas de contornar problemas, o livro também trata de temas como amizade, a busca pela popularidade e os relacionamentos familiares. A relação de Greg com sua família é uma das partes mais hilárias, especialmente com seu irmão mais novo, Manny, que é tratado como um "bebê da casa" apesar de ser bem capaz de criar problemas para Greg. Já a interação de Greg com seus pais é recheada de momentos em que ele tenta enganá-los ou manipular as situações para seu benefício, criando uma dinâmica engraçada de mal-entendidos.
O estilo de escrita de Jeff Kinney é simples, mas com uma grande dose de humor, o que torna a leitura leve e divertida, sendo uma excelente pedida para jovens leitores. O uso de ilustrações complementa a narrativa, com desenhos simples que expressam os sentimentos e as situações em que Greg se encontra, tornando a experiência de leitura ainda mais divertida e dinâmica. As ilustrações têm um toque cômico, o que faz com que até os momentos mais comuns da história se tornem hilariantes.
Em termos de enredo, o livro é bem estruturado para manter o interesse do leitor, com Greg constantemente se metendo em novas enrascadas, o que cria uma sequência de eventos que, apesar de simples, são altamente divertidos e agradáveis de acompanhar. A história, embora não tenha grandes reviravoltas dramáticas, se destaca pela autenticidade e pela representação de como um adolescente vê o mundo ao seu redor, com um olhar cínico, porém com uma sinceridade que cativa.
Em suma, "Diário de um Banana 1" é uma leitura descomplicada e repleta de humor que aborda questões cotidianas de forma inteligente e divertida. A obra se destaca por sua capacidade de fazer rir, ao mesmo tempo em que oferece um retrato honesto da vida adolescente. É uma leitura ideal para aqueles que buscam uma história leve e engraçada, com um toque de nostalgia sobre a juventude e seus dilemas.',0, 5);

INSERT INTO RESENHAS  (res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao) VALUES 
(5, 14,'Viagem ao Centro da Terra','Viagem ao Centro da Terra, de Júlio Verne, é uma das obras mais emblemáticas do autor francês, que revolucionou o gênero de ficção científica com sua capacidade de combinar aventura, imaginação e ciência. Publicado pela primeira vez em 1864, o livro é uma fascinante jornada pelo desconhecido, repleta de mistérios e descobertas, que começa na Terra e leva os personagens a um universo subterrâneo, ao mesmo tempo surpreendente e perigoso.
A história é narrada por Axel, um jovem estudante de ciências, que, junto de seu tio, o professor Lidenbrock, e do guia Hans, embarca em uma jornada ousada e científica para explorar o interior do planeta. Tudo começa quando o professor Lidenbrock encontra um manuscrito antigo que revela um caminho para o centro da Terra, escrito por um alquimista medieval. Ao decifrar a mensagem codificada, Lidenbrock decide realizar uma expedição para explorar o desconhecido, sem considerar os perigos que essa jornada poderia representar. O entusiasmo do professor é contagiante, mas Axel, embora interessado, sente uma crescente apreensão sobre os desafios da expedição.
O livro, por si só, é uma reflexão sobre a ciência e a busca pelo conhecimento. Júlio Verne, embora já tenha sido considerado um visionário em sua época, leva seus personagens a um mundo onde a ciência é a chave para a compreensão do universo e a superação dos desafios. As paisagens subterrâneas, descritas com um detalhamento impressionante para a época, fazem o leitor mergulhar em um mundo surreal e fantástico, mas sempre com um toque de plausibilidade científica. Verne, aliás, é mestre em balancear o fantástico e o possível, e o caminho para o centro da Terra é repleto de situações inusitadas que desafiam os limites do imaginável.
À medida que os personagens avançam na jornada, a narrativa se enche de tensão e emoção. A escuridão crescente, os obstáculos naturais e a constante incerteza sobre o que pode vir a seguir geram uma atmosfera de suspense e de mistério. Em muitos momentos, Verne utiliza a linguagem científica de forma acessível, explicando fenômenos geológicos e naturais com uma precisão admirável. Essa abordagem cria um senso de realismo e plausibilidade, o que torna a viagem dos personagens, apesar de sua fantástica natureza, algo crível.
Além dos aspectos científicos, a obra também possui uma forte carga de aventura. Os três personagens principais enfrentam inúmeros perigos: cavernas imensas, mares subterrâneos, animais pré-históricos e até o próprio medo do desconhecido. É uma jornada que testa suas forças físicas e psicológicas. O professor Lidenbrock, com seu espírito audaz e obstinado, representa a busca insaciável pela verdade, enquanto Axel, com sua hesitação e dúvidas, personifica o leitor cético e preocupado. A relação entre os dois, marcada por momentos de frustração e compreensão mútua, é um dos pilares que sustentam o enredo. Hans, o guia islandês, também desempenha um papel crucial, com sua calma e competência, trazendo equilíbrio ao grupo e provendo uma base prática e técnica para a missão.
O ponto alto da obra está nas descobertas feitas pelo trio, que passa a conhecer paisagens e seres de um mundo completamente desconhecido. A descrição de cavernas imensas, fontes subterrâneas e até de criaturas fantásticas, como dinossauros e outros seres pré-históricos, transporta o leitor para um universo onde a imaginação é estimulada. Mesmo em seus momentos mais tensos e perigosos, o livro nunca perde sua aura de maravilhamento e curiosidade científica, com o autor constantemente destacando o poder da ciência e da razão para desvendar os mistérios do mundo.
O final do livro, que traz uma conclusão que, embora não seja o ápice de uma grande batalha ou confronto, traz uma surpresa gratificante, não deixa de reafirmar a mensagem central da obra: a jornada do conhecimento é repleta de riscos, mas também de recompensas. O fim da viagem, ao mesmo tempo que encerra o mistério do centro da Terra, abre novas possibilidades e deixa no ar a sensação de que a busca pelo desconhecido é eterna.
Viagem ao Centro da Terra é uma obra que, mesmo com o passar dos anos, continua a fascinar os leitores por sua riqueza imaginativa e pela forma como Júlio Verne anteviu muitos conceitos científicos antes de sua época. Ao unir ciência, aventura e uma boa dose de suspense, o autor cria uma narrativa que é tanto uma lição sobre o conhecimento quanto um convite ao maravilhoso e ao desconhecido. O livro é uma viagem inesquecível, que ultrapassa os limites do que é possível e nos faz refletir sobre o potencial infinito da exploração humana.',0, 5);


INSERT INTO RESENHAS  (res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao) VALUES 
(5,15 ,'O Homem Cão o senhor das Pulgas','O Homem Cão: O Senhor das Pulgas, escrito por Dav Pilkey, é o segundo livro da série que acompanha as aventuras de George e Harold, os criadores de um super-herói muito peculiar: o Homem Cão. Esta obra, como as anteriores da série, é uma mistura de comédia e ação, com uma narrativa divertida, cheia de criatividade e reviravoltas absurdas. Ela também segue a linha irreverente e cômica que tornou Dav Pilkey famoso, especialmente por sua habilidade de capturar o espírito de aventura e humor que ressoa com leitores de todas as idades.
O enredo de O Senhor das Pulgas" gira em torno das novas peripécias de George e Harold, dois meninos travessos e criativos, que, ao invés de se conformarem com as regras e com a vida escolar, inventam histórias e personagens fantásticos. O personagem principal desta vez é o Homem Cão, uma espécie de super-herói que possui poderes extraordinários, mas com um toque de comédia que faz dele um anti-herói peculiar. Em sua nova aventura, o Homem Cão se vê diante de uma ameaça inusitada: o "Senhor das Pulgas", um vilão que parece ser uma mistura de ciência maluca e uma ideia bizarra de um monstro que causa caos em qualquer lugar que vá.
O livro é um exemplo claro do estilo único de Pilkey, que combina humor nonsense com uma trama de ação que nunca se leva muito a sério. As ilustrações são uma parte fundamental dessa experiência, com desenhos simples e cartunescos que trazem vida à narrativa de maneira hilária e muitas vezes surreal. A arte tem um tom infantil, mas ao mesmo tempo é cheia de detalhes engraçados que fazem o leitor se envolver ainda mais com a história.
Um dos elementos mais marcantes do livro é a maneira como Pilkey se utiliza de elementos de humor físico e situações exageradas para atrair a atenção do público jovem. George e Harold não apenas criam o Homem Cão, mas acabam se metendo em várias confusões, sendo os verdadeiros "heróis" da história. Embora eles sejam crianças travessas, suas intenções geralmente são boas, o que dá ao livro um toque de leveza e carisma.
Em termos de mensagens e temas, "O Homem Cão: O Senhor das Pulgas" aborda a importância da criatividade e da imaginação. Através dos personagens principais e suas invenções malucas, o livro estimula a liberdade de expressão e o pensamento criativo, além de brincar com a ideia de que todos podem ser heróis, não importa quão estranhos ou incomuns possam parecer. A obra também faz uma crítica ao comportamento de alguns adultos, apresentando figuras de autoridade que são tão ineficazes quanto as crianças tentam fugir ou enganar.
Além disso, a interação de George e Harold com o Homem Cão também toca em temas como amizade e o poder de trabalhar em equipe. A relação entre os dois amigos é uma das mais divertidas e genuínas do livro, o que traz uma sensação de camaradagem e complicidade entre eles. O livro também aborda um tema presente em muitas obras de Pilkey, que é o contraste entre a visão de mundo das crianças e a das figuras de autoridade, sempre retratadas de forma humorística e exagerada.
Em suma, O Homem Cão: O Senhor das Pulgas é uma leitura cativante e cheia de diversão, ideal para leitores mais jovens, mas também capaz de agradar aos adultos que buscam uma dose de nostalgia e humor. Com sua narrativa leve e irreverente, a obra mantém o tom engraçado e excêntrico da série, ao mesmo tempo que entrega uma história cheia de ação e aventura. A combinação de ilustrações engraçadas, personagens cativantes e uma trama que não se leva muito a sério faz deste livro uma leitura recomendada para quem gosta de boas risadas e histórias inusitadas.
',0, 4);

INSERT INTO RESENHAS  (res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao) VALUES 
(5, 16,'O livro da filosofia','"O Livro da Filosofia", publicado pela editora Globo Livros, é uma obra de abordagem acessível e esclarecedora, que se propõe a apresentar as principais ideias e pensadores da filosofia de uma maneira simples, mas sem perder a profundidade do conteúdo. Através de uma narrativa clara e objetiva, o livro busca contextualizar o surgimento das grandes correntes filosóficas ao longo da história e como elas continuam a influenciar nosso pensamento e comportamento até os dias atuais.
O livro se organiza em uma linha do tempo que percorre desde os filósofos da Antiguidade, como Sócrates, Platão e Aristóteles, até pensadores contemporâneos, abordando de maneira detalhada os principais marcos da filosofia ocidental. Ele é ideal para quem está começando a se interessar pela filosofia ou para aqueles que desejam um panorama geral sobre os temas que moldaram o pensamento humano, mas não possuem o tempo ou a disposição para se aprofundar em textos filosóficos mais densos.
Com uma escrita objetiva e sem o uso de jargões acadêmicos pesados, a obra busca descomplicar as ideias de pensadores que, muitas vezes, podem parecer complexos e difíceis de entender. O livro consegue transmitir essas ideias de forma concisa e acessível, sem simplificar demais o conteúdo, mantendo o respeito pela profundidade dos pensamentos apresentados. O autor faz isso com clareza e didática, com o objetivo de permitir ao leitor uma compreensão abrangente dos conceitos discutidos, sem que seja necessário ter um conhecimento prévio na área.
Além disso, "O Livro da Filosofia" é enriquecido por ilustrações e gráficos que facilitam a compreensão do conteúdo e tornam a leitura mais agradável. As imagens ajudam a ilustrar conceitos-chave, como a estrutura do pensamento de determinados filósofos, ou a forma como suas ideias dialogaram com as de outros pensadores. Esses recursos visuais também ajudam a quebrar a linearidade da leitura e a manter o interesse do leitor, além de facilitar o entendimento de temas mais abstratos ou complicados.
O livro abrange uma vasta gama de temas filosóficos, desde as questões existenciais levantadas pelos grandes nomes da filosofia grega, como os dilemas éticos de Platão e Aristóteles, até discussões sobre liberdade, política, ciência e moral abordadas por pensadores modernos como Kant, Nietzsche e Marx. Essa diversidade de tópicos é uma das forças da obra, pois permite ao leitor perceber como a filosofia se desenvolveu ao longo dos séculos e como os filósofos abordaram questões fundamentais sobre a vida, a sociedade, o conhecimento e o comportamento humano.
Outro ponto positivo é que, mesmo sendo uma introdução à filosofia, o livro não se limita a apresentar as ideias filosóficas de maneira superficial. Ao contrário, ele promove uma reflexão mais profunda sobre as questões que os filósofos levantaram, permitindo que o leitor faça conexões entre as ideias de diferentes pensadores e compreenda as repercussões dessas ideias na sociedade e no pensamento moderno. Em vez de simplesmente transmitir fatos ou resumos das filosofias, o livro provoca o leitor a pensar criticamente sobre o legado filosófico e a questionar as questões que surgem da leitura.
No entanto, a obra pode não ser suficiente para quem deseja um estudo mais aprofundado sobre filosofia. Como uma introdução, ela serve bem ao seu propósito, mas não explora as ideias de cada filósofo em profundidade, nem se propõe a debater as interpretações mais complexas e as diversas correntes de pensamento. Isso significa que, para um público mais avançado ou para aqueles que buscam uma compreensão mais detalhada de algum filósofo específico, o livro pode ser apenas o ponto de partida, deixando a desejar em termos de análises mais complexas.
Em resumo, "O Livro da Filosofia" da Globo Livros é uma excelente introdução ao vasto universo do pensamento filosófico. Ele consegue equilibrar clareza e profundidade, tornando as ideias filosóficas acessíveis a um público amplo e interessado. Se você está começando a explorar a filosofia ou deseja obter uma visão geral das principais correntes filosóficas ao longo da história, essa obra é uma excelente escolha, oferecendo um panorama bem estruturado, fácil de entender e visualmente estimulante.',0, 4);


INSERT INTO RESENHAS  (res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao) VALUES 
(5,17,'Alice no País das Maravilhas','"Alice no País das Maravilhas", escrito por Lewis Carroll e publicado pela primeira vez em 1865, é uma das obras mais conhecidas e amadas da literatura infantil, que, com sua mistura de fantasia, surrealismo e crítica social, conquistou leitores de todas as idades ao redor do mundo. O livro segue Alice, uma menina curiosa e sonhadora, que cai em um buraco de coelho e se vê em um mundo extraordinário, cheio de personagens excêntricos e situações absurdas. O enredo não segue uma estrutura tradicional e linear, mas sim uma série de encontros e episódios desconexos, onde Alice interage com uma galeria de figuras bizarras e misteriosas.
A obra se inicia de forma simples, com Alice entediada à beira do rio, até que, ao ver um coelho branco vestido e apressado, ela decide segui-lo. A partir desse momento, a narrativa se desenrola em um turbilhão de eventos fantásticos, e Alice começa a perceber que as regras do mundo que conhecia não se aplicam ao País das Maravilhas. Esse novo universo é regido por lógicas e raciocínios absurdos, nos quais a razão e o senso comum são desafiados a todo momento.
Alice, durante sua jornada, encontra personagens peculiares, como o Coelho Branco, a Lagarta, o Gato de Cheshire, a Rainha de Copas e muitos outros. Cada um deles oferece uma visão única do mundo, sendo alguns enigmáticos, outros paradoxais ou apenas ilógicos. A conversa com a Lagarta, por exemplo, gira em torno da identidade de Alice e de como ela, ao crescer e mudar de tamanho constantemente, tem dificuldades para se entender. Já o Gato de Cheshire, com seu sorriso enigmático, responde a perguntas com mais perguntas, deixando Alice (e o leitor) mais confusa do que antes.
As situações absurdas que Alice vivencia no País das Maravilhas são emblemáticas do estilo de Carroll, que mistura o humor nonsense com uma crítica velada às convenções sociais e às normas rígidas da sociedade vitoriana. A famosa cena do chá com o Chapeleiro Maluco, a Lebre de Março e o Rouxinol, por exemplo, é uma crítica direta à imperturbabilidade e às rígidas normas sociais da época. Tudo nesse mundo parece estar em constante transformação, como se as regras da lógica fossem desfeitas a cada passo, o que transmite uma sensação de caos e instabilidade que é ao mesmo tempo desconcertante e fascinante.
Alice, como personagem, representa a curiosidade infantil e a busca incessante por respostas, ainda que as respostas nem sempre façam sentido ou conduzam a lugar algum. Ela tenta entender o significado das coisas que vê, mas o País das Maravilhas, com sua lógica insana, resiste a qualquer tentativa de explicação racional. Essa busca por significado, em um universo tão ilógico, torna a leitura não apenas uma experiência fantástica, mas também filosófica, ao explorar a natureza do conhecimento e da percepção.
Outro ponto notável no livro é a maneira como Carroll brinca com a linguagem e os jogos de palavras. A obra está cheia de trocadilhos, paradoxos e diálogos que, muitas vezes, parecem não ter sentido, mas que, ao mesmo tempo, questionam a própria natureza da linguagem e da comunicação. Por exemplo, na famosa cena do julgamento da Carta de Tais, as acusações são baseadas em raciocínios tão ilógicos e absurdos que se tornam um reflexo satírico da burocracia e das instituições jurídicas de sua época.
Apesar de ser, à primeira vista, uma obra voltada para o público infantil, "Alice no País das Maravilhas" possui camadas de significados que vão muito além da superfície. Através de sua narrativa fantasiosa e surreal, o livro toca em questões filosóficas, como a identidade, a realidade, a autoridade e a ordem social. Carroll, com sua habilidade para criar um mundo totalmente novo e inusitado, oferece uma experiência literária que vai além do simples entretenimento, incentivando reflexões mais profundas sobre a natureza da realidade e do comportamento humano.
O desfecho da história, embora aparentemente sem uma conclusão definitiva, reflete essa própria característica do livro. Ao acordar de seu sonho, Alice volta ao mundo real, mas, como leitor, fica a sensação de que o País das Maravilhas ainda está com ela, na forma de suas perguntas sem respostas, seus paradoxos e sua constante busca por sentido.
"Alice no País das Maravilhas" é uma obra atemporal que, com sua narrativa inovadora e cheia de surpresas, continua a ser uma das mais celebradas da literatura mundial. Sua mistura única de fantasia, humor, crítica social e reflexão filosófica torna-a um livro fascinante para todas as idades, capaz de despertar a imaginação e questionar a percepção do mundo de forma profunda e divertida.',0, 4);


INSERT INTO RESENHAS  (res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao) VALUES 
(5, 18,'Os sete maridos de Evelyn Hugo','"Os Sete Maridos de Evelyn Hugo", escrito por Taylor Jenkins Reid, é uma obra que cativa pela sua habilidade em tecer uma narrativa envolvente sobre fama, identidade e as complexas relações humanas. Ambientada no glamour e na decadência de Hollywood, o livro mistura mistério, drama e reflexões profundas sobre a vida e as escolhas de uma mulher que, à primeira vista, parece ser apenas mais uma estrela de cinema. No entanto, à medida que a história se desenrola, a verdadeira essência de Evelyn Hugo se revela, cheia de camadas e nuances que surpreendem e emocionam o leitor.
A trama é narrada por Monique Grant, uma jornalista relativamente desconhecida que é escolhida por Evelyn para escrever sua biografia, algo que parece ser um grande golpe para sua carreira. Monique, no entanto, logo descobre que a tarefa de contar a história de Evelyn é muito mais complexa e profunda do que ela imaginava. A lendária atriz, que foi uma das maiores estrelas de Hollywood nos anos 50 e 60, decide revelar sua história de vida para o mundo, mas com uma condição: Monique deve ser a responsável por registrar sua versão dos fatos. Assim, o livro se torna um relato duplo, onde a história da própria Evelyn é intercalada com as reflexões e emoções de Monique, que, à medida que conhece mais sobre a vida da atriz, começa a lidar com seus próprios dilemas pessoais.
A vida de Evelyn Hugo é marcada por sete casamentos, e cada um deles representa uma fase distinta de sua vida e carreira. A escolha de Evelyn de ter sete maridos não é apenas uma questão de busca por amor ou estabilidade, mas também um reflexo de sua necessidade de se moldar e se adaptar às exigências de Hollywood e da sociedade da época. Cada casamento, com suas complicações e segredos, revela um lado de Evelyn que a mídia nunca viu, e a complexidade de sua vida pessoal, muitas vezes sacrificada em nome de sua carreira, começa a ser desvendada aos poucos. As histórias de seus maridos são, em muitos aspectos, paralelas às suas próprias lutas e vitórias, refletindo as escolhas difíceis que ela teve que fazer ao longo de sua vida.
A autora consegue, com maestria, criar um personagem que é simultaneamente admirado e criticado. Evelyn é, sem dúvida, uma mulher forte, que lutou para conquistar seu lugar em um mundo dominado por homens, mas, ao mesmo tempo, é uma mulher que fez escolhas difíceis, algumas das quais a tornaram impopular ou incompreendida. O livro não busca pintar Evelyn como uma heroína clássica, mas sim como uma pessoa real, cheia de falhas, arrependimentos e, principalmente, coragem. Seu caráter é desafiado o tempo todo, tanto pelas circunstâncias quanto pelos outros, mas sua resiliência a torna uma personagem inesquecível, com a qual é impossível não simpatizar, mesmo nos momentos mais sombrios de sua trajetória.
O relacionamento entre Evelyn e Monique também é um dos pontos centrais do livro, pois à medida que a biografia se desenrola, Monique começa a entender que, apesar de todas as diferenças entre elas, há algo muito profundo que as conecta. A autora brinca com a ideia de que as duas mulheres, cada uma com suas próprias batalhas e desejos, têm mais em comum do que se poderia imaginar. O processo de escrita da biografia acaba sendo uma jornada de autoconhecimento para Monique, que também enfrenta suas próprias questões de identidade e busca por respostas em relação ao seu passado.
A maneira como a autora explora os temas do amor, da lealdade, da ambição e do sacrifício é tocante. Evelyn é uma mulher que, por mais que tenha alcançado o auge do sucesso, nunca conseguiu encontrar a verdadeira felicidade, em grande parte devido aos compromissos que fez em sua vida pessoal e profissional. Seu amor por Celia St. James, uma outra atriz famosa, é o centro emocional do livro, e é através desse relacionamento que Evelyn se torna ainda mais humana, à medida que enfrenta as dificuldades de viver em uma sociedade que não aceita o amor entre pessoas do mesmo sexo.
O final de "Os Sete Maridos de Evelyn Hugo" é devastador e profundamente satisfatório. A autora encerra a história de uma maneira que mistura a tragédia com a redenção, levando o leitor a refletir sobre as escolhas que fazemos ao longo da vida e sobre o que realmente importa quando se olha para trás. O que Evelyn Hugo nos ensina, no final das contas, é que a verdadeira liberdade e felicidade só podem ser alcançadas quando se é honesto consigo mesmo, independentemente do custo que isso possa ter para a imagem pública ou para os outros.
Em resumo, "Os Sete Maridos de Evelyn Hugo" é uma obra cativante e emocionalmente rica que mergulha nos bastidores de uma vida de glamour e sacrifícios. Com personagens bem construídos e uma trama envolvente, Taylor Jenkins Reid consegue não só entreter, mas também provocar uma reflexão profunda sobre o preço da fama, o amor, a identidade e o que significa ser verdadeiramente livre. A história de Evelyn é, sem dúvida, uma das mais poderosas e complexas do cenário literário contemporâneo, e seu legado permanecerá com o leitor muito tempo após o término da leitura.',0, 5);




INSERT INTO RESENHAS  (res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao) VALUES 
(4,19 ,'Quarta Asa','"Quarta Asa", escrito por Carolina Munhóz e Sophia Abrahão, é uma obra que mistura elementos de fantasia, aventura e reflexão sobre questões contemporâneas, envolvendo jovens leitores em uma trama emocionante e cheia de reviravoltas. O livro transporta o público para um universo onde o fantástico e o real se encontram de maneira intrigante, explorando a jornada de personagens que se veem diante de escolhas e desafios que vão muito além da compreensão inicial do que é possível ou impossível.
A história segue a vida de três protagonistas que, em algum momento de suas existências, se veem confrontados com o surgimento de uma quarta asa, algo que muda profundamente suas realidades e identidades. Cada um deles, de forma única, enfrenta um momento de grande transformação e revelação, o que propicia uma análise da individualidade e do amadurecimento. Esse "poder" simbólico da quarta asa não é apenas literal, mas também funciona como uma metáfora para as possibilidades de autodescoberta e as complexas questões existenciais que todos os jovens enfrentam.
A trama é envolvente e, ao mesmo tempo, provoca reflexão. A autora usa o conceito de asas de uma maneira que evoca tanto liberdade quanto responsabilidade, levando os personagens a enfrentarem dilemas sobre a aceitação de seus novos destinos e os impactos que esses poderes têm sobre suas relações pessoais e sociais. O surgimento de uma quarta asa, portanto, é algo que não apenas os muda fisicamente, mas também altera a forma como eles se relacionam com o mundo e consigo mesmos. A narrativa é, assim, um convite para que o leitor explore questões internas de identidade, aceitação e o desejo de se encaixar, mas também sobre a necessidade de se libertar de expectativas externas.
Além disso, a construção dos personagens é um dos grandes trunfos de "Quarta Asa". Cada um deles tem suas peculiaridades, inseguranças e desejos, o que os torna bastante humanos e próximos do leitor. As interações entre os personagens são cheias de emoção e complexidade, com destaque para a amizade e os laços que são testados e fortalecidos ao longo da história. Os dilemas que enfrentam são universais, mas a forma como cada um lida com sua nova realidade traz uma camada adicional de profundidade à narrativa, que vai além da simples ação fantástica.
A escrita de Carolina Munhóz e Sophia Abrahão é fluida e acessível, conseguindo cativar não só os jovens leitores, mas também aqueles que buscam uma leitura leve, mas com substância. A narrativa é envolvente, e as autoras têm o talento de manter o suspense e a curiosidade ao longo do livro, criando uma atmosfera de mistério e aventura, enquanto também introduzem questões filosóficas e existenciais de forma sutil. O ritmo da história é bem equilibrado, alternando momentos de tensão e reflexão, o que mantém o leitor interessado do início ao fim.
O livro também se destaca por sua capacidade de tratar de temas profundos, como o autoconhecimento, o poder da amizade e a busca pela identidade, sem perder o toque de fantasia que o torna único. A obra convida o leitor a refletir sobre o impacto das escolhas que fazemos e a entender que, mesmo quando nos sentimos perdidos ou diferentes, temos o poder de nos reinventar e de encontrar um caminho próprio, que nos permita alçar voo e explorar as inúmeras possibilidades da vida.
Em resumo, "Quarta Asa" é uma obra encantadora e reflexiva, que mistura fantasia e temas contemporâneos de maneira habilidosa. Com personagens cativantes e uma trama que instiga a reflexão, o livro é uma excelente escolha para aqueles que desejam uma leitura envolvente, que ao mesmo tempo toca em questões emocionais e existenciais profundas, sem deixar de lado o elemento fantástico que a torna uma experiência única e inesquecível.', 0, 4);












INSERT INTO RESENHAS  (res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao) VALUES 
(4,20,'O horizonte mora em um dia cinza
','"O Horizonte Mora em um Dia Cinza", escrito por Vitor Martins, é um romance que mergulha nas complexidades da adolescência, da identidade e dos primeiros amores, com uma escrita sensível e envolvente que captura a essência de momentos de descoberta e autoconhecimento. A história acompanha Pedro, um jovem de 17 anos, que vive na cidade de São Paulo e está em um período de transição entre a adolescência e a vida adulta. Ele se vê diante de desafios que envolvem sua sexualidade, sua relação com os outros e consigo mesmo, além das questões familiares e sociais que o cercam.
O enredo gira em torno do vínculo que Pedro desenvolve com o seu amigo Gabriel, um jovem que também enfrenta as suas próprias questões pessoais e com quem ele acaba criando uma conexão afetiva profunda. O relacionamento deles não é imediato, mas se constrói aos poucos, a partir de diálogos sinceros e de uma intimidade que vai se formando com o tempo. A história de Pedro é, ao mesmo tempo, uma reflexão sobre o amadurecimento emocional e a busca por pertencimento, características que são vividas de uma maneira intensa e muitas vezes conflituosa.
O autor, com uma narrativa rica em detalhes, nos leva aos bastidores da mente de Pedro, deixando claro as dúvidas e inseguranças que ele enfrenta ao tentar se entender enquanto pessoa e se relacionar com aqueles que ama. O grande trunfo da obra está em sua capacidade de humanizar seus personagens, tornando-os multifacetados, com medos, desejos, falhas e qualidades, o que gera uma identificação imediata com o leitor. A escrita de Vitor Martins é delicada, mas sem ser piegas, e consegue transitar entre momentos de leveza e profundidade, fazendo com que a história se desdobre com uma naturalidade encantadora.
A cidade de São Paulo também desempenha um papel importante na construção da narrativa, funcionando como um pano de fundo que reflete o caos e a beleza da vida urbana, além de proporcionar uma atmosfera única para os eventos que se desenrolam. Martins retrata o cotidiano com uma fluidez que aproxima o leitor da realidade de seus personagens, e a cidade se torna quase uma personagem por si só, com suas ruas, esquinas e ritmos que influenciam os acontecimentos e as emoções dos personagens.
Outro ponto significativo do livro é a forma como ele aborda a sexualidade de maneira sensível, sem recorrer a estereótipos ou a uma narrativa convencional. A sexualidade de Pedro e a descoberta de sua própria identidade são tratadas de forma natural e sem pressa, refletindo um processo muitas vezes difícil e contraditório, mas também cheio de beleza e potencial para transformação. O romance entre Pedro e Gabriel, embora não seja o foco central da história, cresce de maneira orgânica, como um reflexo da busca por aceitação e por entender o que é realmente importante para o próprio bem-estar.
A relação de Pedro com sua família também é explorada de maneira complexa. Sua convivência com os pais e a busca por sua aprovação e compreensão, especialmente no que diz respeito à sua identidade, é um dos aspectos que mais emocionam na obra. A dinâmica familiar, repleta de amor, mas também de frustrações e desconexões, é uma representação honesta de como as relações familiares podem ser tanto um apoio quanto um desafio.
O livro também trata de temas como amizade, lealdade e as dificuldades de lidar com os sentimentos e expectativas que nos são impostos pela sociedade. O "dia cinza" do título simboliza as incertezas e os momentos difíceis de nossa vida, mas também se refere ao processo de crescer e aprender a conviver com a complexidade do mundo ao nosso redor. O horizonte, neste contexto, é algo que está sempre presente, mesmo quando está encoberto pela névoa das dificuldades do dia a dia. Isso faz com que a obra tenha uma mensagem de esperança, pois, mesmo quando o céu está nublado, sempre há uma possibilidade de mudança e crescimento.
"O Horizonte Mora em um Dia Cinza" é uma história que toca o coração, pois, ao tratar da jornada emocional de Pedro, Vitor Martins consegue criar uma narrativa universal, que fala sobre a busca por identidade, os desafios das relações pessoais e a construção do próprio caminho. A escrita fluida e a empatia com que o autor se dedica aos seus personagens fazem com que a obra seja uma leitura encantadora e tocante, que ressoa profundamente com qualquer pessoa que já tenha se sentido à deriva, à espera de encontrar seu próprio horizonte. A beleza do livro está na sua capacidade de abordar questões tão significativas e, ao mesmo tempo, retratar a adolescência como um período de transformação que, apesar dos dias cinzentos, sempre oferece novas possibilidades.',0, 4);












INSERT INTO RESENHAS  (res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao) VALUES 
(4,21,'Verity','"Verity", escrito por Colleen Hoover, é um suspense psicológico que mistura mistério, romance e tensão de uma forma intensa e inesperada. A autora, conhecida por suas histórias emocionantes e envolventes, se arrisca aqui em um gênero mais sombrio, criando uma trama que mantém o leitor na ponta da cadeira desde as primeiras páginas. O livro segue Lowen Ashleigh, uma escritora que, em um momento de dificuldades financeiras e profissionais, é contratada para terminar a série de livros de uma autora famosa chamada Verity Crawford. Quando Lowen começa a trabalhar na casa de Verity para estudar seus cadernos e anotações, ela se vê imersa em uma história sombria, cheia de segredos e verdades ocultas que começam a mexer com sua própria percepção da realidade.
A história começa de maneira relativamente tranquila, com Lowen indo até a casa de Verity, que está em coma após um acidente. O que inicialmente parece uma simples tarefa de finalizar uma série de livros se transforma em uma jornada de descobertas e mistérios perturbadores. Ao vasculhar os cadernos de Verity, Lowen encontra uma autobiografia não publicada, onde a autora revela detalhes perturbadores sobre sua vida e sua família, incluindo segredos que parecem ir além de uma simples narrativa ficcional. Conforme Lowen lê, ela começa a se questionar sobre o que é real e o que pode ser manipulação, e os limites entre a ficção e a realidade começam a se misturar de maneira assustadora.
O suspense psicológico é um dos grandes pontos fortes de "Verity". Colleen Hoover cria uma atmosfera de tensão constante, deixando o leitor desconfortável e cheio de perguntas, especialmente em relação ao comportamento de Verity e de sua família. O livro não é apenas uma narrativa de mistério, mas também um estudo psicológico dos personagens, suas motivações e os segredos que carregam. Os sentimentos de Lowen em relação à situação de Verity e a convivência com o marido dela, Jeremy, adicionam uma camada de complexidade ao enredo, tornando as relações ainda mais instáveis e imprevisíveis.
O romance entre Lowen e Jeremy também desempenha um papel significativo na história, mas não é o foco principal do livro. O relacionamento deles é intenso, mas permeado por uma grande carga emocional e moral, já que Lowen começa a se envolver com um homem cuja esposa está em coma, e à medida que os segredos de Verity vão sendo revelados, ela fica mais confusa sobre até que ponto pode confiar no que está acontecendo. A autora coloca o leitor em um jogo de sedução e desconfiança, onde não é claro se as intenções de Jeremy são genuínas ou se ele está escondendo algo crucial.
O enredo é habilmente construído, com várias reviravoltas que pegam o leitor de surpresa e desafiam suas suposições sobre os personagens. O maior trunfo de "Verity" é justamente esse jogo de enganos e a maneira como Hoover manipula as expectativas do público. Quando parece que a história está indo em uma direção, um novo detalhe ou descoberta muda tudo. Essa imprevisibilidade mantém a história instigante, com o leitor constantemente questionando os limites da verdade e da mentira.
Além da trama principal, "Verity" também oferece uma reflexão sobre o que significa confiar nas palavras de alguém, especialmente quando essas palavras são escritas ou contadas de maneira a manipular a percepção do outro. A obra lida com os temas da culpa, do arrependimento e da moralidade, desafiando o leitor a refletir sobre até onde uma pessoa pode ir para alcançar seus objetivos ou proteger seus segredos.
A escrita de Colleen Hoover, sempre fluida e envolvente, é um dos pilares que sustentam a narrativa. Ela consegue criar uma tensão palpável, equilibrando momentos de introspecção com outros de puro suspense. A autora também se destaca na construção de personagens complexos e imperfeitos, cujas motivações e ações são difíceis de decifrar, o que só aumenta o mistério e a complexidade da trama.
Em resumo, "Verity" é uma obra que vai muito além de um simples suspense psicológico. Colleen Hoover consegue criar uma narrativa inquietante, onde os mistérios e os segredos se desdobram de maneiras surpreendentes, mantendo o leitor ansioso por cada página. O romance e o suspense se entrelaçam de forma a desafiar as percepções do leitor, criando uma história que é ao mesmo tempo perturbadora, envolvente e, acima de tudo, cheia de reviravoltas. É um livro que não só cativa, mas também provoca reflexões sobre a moralidade, a verdade e os limites da confiança humana.',0, 5);




INSERT INTO RESENHAS  (res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao) VALUES 
(4,22,'É Assim Que Acaba','"É Assim Que Acaba", de Colleen Hoover, é um romance contemporâneo que explora temas profundos e complexos, como abuso emocional, relacionamentos tóxicos e a luta pela superação pessoal. Com sua escrita envolvente e personagens intensos, Hoover entrega uma narrativa que não apenas cativa, mas também faz refletir sobre o que significa amar e até onde se pode ir para preservar a própria dignidade e segurança. O livro gira em torno de Lily Bloom, uma jovem que, após enfrentar dificuldades na infância, tenta construir uma vida nova e independente em Boston, onde começa a se envolver com Ryle Kincaid, um neurocirurgião bem-sucedido, mas que esconde um lado sombrio de sua personalidade.
Desde o início, a autora nos apresenta Lily como uma mulher forte, mas vulnerável, que busca se curar de suas feridas passadas. Sua história começa com a morte de seu pai e a visita ao túmulo, onde ela tem uma espécie de revelação sobre o que quer para sua vida. Logo, ela se apaixona por Ryle, que parece ser a pessoa ideal: encantador, inteligente e atraente. No entanto, a relação com Ryle se revela uma montanha-russa emocional, e logo se tornam evidentes os sinais de um relacionamento abusivo, não físico inicialmente, mas psicológico e emocional, com o controle e manipulação sutis por parte dele.
O que torna "É Assim Que Acaba" ainda mais tocante é que Lily não está apenas lidando com Ryle, mas também com o ressoar de seu próprio passado, particularmente com a relação traumática que ela teve com seu pai, um homem violento que deixou marcas profundas em sua vida. Em uma narrativa paralela, Lily começa a revisitar seu relacionamento com Atlas Corrigan, um jovem que ela conheceu quando era adolescente e que a ajudou nos momentos mais difíceis de sua vida. Atlas é a antítese de Ryle: compreensivo, gentil e amoroso. Ao longo da trama, Lily precisa enfrentar os fantasmas do passado e decidir se ela tem forças para recomeçar e lutar por uma vida livre da violência e do medo.
A construção do relacionamento entre Lily e Ryle é tensa e desgastante, o que faz com que o leitor sinta, na pele, o dilema vivido pela protagonista. O amor que ela sente por Ryle é real e forte, mas também é profundamente tóxico. Hoover faz um excelente trabalho em mostrar como os ciclos de abuso emocional podem ser difíceis de romper, especialmente quando o agressor se apresenta com desculpas convincentes e juras de que vai mudar. A autora, com sensibilidade, ilustra as dificuldades de uma vítima de abuso em encontrar força para se libertar, e também os efeitos devastadores que isso tem na autoestima e nas escolhas de vida de uma pessoa.
O romance também trata da questão do perdão e da coragem. Lily precisa aprender a perdoar a si mesma e a compreender que não pode controlar os comportamentos de outra pessoa, nem ser responsável por mudar alguém. Além disso, o livro oferece uma reflexão sobre os padrões que se repetem nas relações, mostrando como, muitas vezes, as experiências passadas moldam a maneira como lidamos com os desafios do presente.
"É Assim Que Acaba" é uma obra dolorosa, mas necessária, pois coloca na mesa a discussão sobre relacionamentos abusivos, um tema muitas vezes ignorado ou tratado de maneira superficial em outras narrativas. Hoover não tem medo de mostrar a complexidade emocional envolvida em situações como essa, e faz isso de forma honesta, sem glamourizar ou minimizar os efeitos do abuso. O livro é sensível, mas também exige força do leitor, pois a dor de Lily é tangível, e suas escolhas, embora difíceis, são profundamente humanas.
O desfecho da obra é impactante e catártico, trazendo uma resolução que, embora dolorosa, é também libertadora. Lily, finalmente, encontra sua própria voz e toma decisões que a levam a um futuro mais seguro e saudável. A autora encerra a história de maneira que transmite esperança, mas também reforça a importância de se colocar em primeiro lugar, de respeitar os próprios limites e de reconhecer que, por mais difícil que seja, é possível encontrar a força para recomeçar e se reinventar.
"É Assim Que Acaba" é, sem dúvida, uma história sobre o fim de um ciclo, mas também sobre o renascimento. Colleen Hoover, com sua escrita direta e comovente, cria uma trama que desafia os leitores a confrontar as realidades difíceis da vida, mostrando que, às vezes, é preciso terminar um capítulo doloroso para que outro mais promissor comece. O livro não apenas toca o coração, mas também provoca uma reflexão sobre o que significa realmente amar e cuidar de si mesmo, sempre colocando a segurança e o bem-estar acima de qualquer outra coisa.', 0, 5);




INSERT INTO RESENHAS  (res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao) VALUES 
(4,23,'É assim que começa
','"É Assim Que Começa", escrito por Lisa Cron, é um livro fascinante que explora as complexidades da narrativa, especificamente sobre como uma história pode cativar o leitor desde o início e envolvê-lo de maneira profunda e emocional. A obra é, na verdade, uma análise do processo de construção de uma história e dos mecanismos psicológicos que fazem com que os leitores se conectem com os personagens e os enredos. Ao longo do livro, Cron oferece insights valiosos sobre como as narrativas funcionam em um nível emocional, desafiando a ideia de que uma boa história se baseia apenas em uma trama bem desenvolvida ou em reviravoltas surpreendentes.
O foco principal de "É Assim Que Começa" é a premissa de que as grandes histórias começam muito antes do primeiro capítulo – elas começam no momento em que o leitor decide abrir o livro. Cron explica como é essencial entender o que cativa um leitor logo nas primeiras páginas e como, muitas vezes, é o início da história que define se o público continuará ou não a jornada. Em vez de ser um manual tradicional sobre técnicas de escrita, o livro é um estudo psicológico que se aprofunda no impacto emocional das narrativas e em como elas têm o poder de manipular os sentimentos e as expectativas dos leitores.
Cron também dedica boa parte do livro a explorar como os elementos internos de uma história, como os desejos e as motivações dos personagens, são fundamentais para que a trama tenha ressonância emocional. A autora descreve a importância de entender o que cada personagem deseja e como essas vontades influenciam a direção da história. Além disso, ela argumenta que uma boa narrativa deve ser capaz de gerar uma conexão imediata entre o leitor e o protagonista, algo que se torna ainda mais relevante quando falamos de histórias que podem ser complexas ou que exigem a suspensão da descrença.
Ao longo do livro, Cron utiliza uma abordagem prática, oferecendo exemplos de grandes obras literárias e desmembrando o que faz com que elas funcionem tão bem. Ela fala sobre o impacto das escolhas feitas no início de uma história – desde a forma como um escritor introduz um personagem até como uma situação inicial pode preparar o terreno para o desenvolvimento da narrativa. A autora também discute a importância do conflito e como ele é um fator chave que, se bem trabalhado desde o início, pode garantir que o leitor se mantenha interessado na história.
A escrita de Lisa Cron é envolvente e repleta de exemplos claros, o que torna o livro não só informativo, mas também muito interessante para quem ama a arte de contar histórias. "É Assim Que Começa" não se destina apenas a escritores, mas também a leitores, pois oferece uma visão sobre o que acontece nos bastidores da narrativa. A autora explica, por exemplo, como cada decisão no desenvolvimento de um personagem ou na construção de uma cena pode ter um efeito profundo na jornada emocional do público. Ela desvenda os mistérios por trás das boas histórias e mostra que, por trás de cada grande narrativa, há uma compreensão do funcionamento emocional do ser humano.
Ao contrário de outros livros sobre escrita, "É Assim Que Começa" não se limita a explicar a estrutura básica de uma história ou a oferecer fórmulas. Cron é muito mais profunda ao abordar os mecanismos emocionais que fazem com que uma história seja memorável, analisando como os leitores respondem a diferentes tipos de conflito, desejo e desenvolvimento de personagem. A autora explora, também, a importância da antecipação e da expectativa, explicando como o primeiro momento de uma história pode acender o interesse do leitor e criar uma ligação imediata com a trama.
"É Assim Que Começa" é, portanto, uma leitura essencial para quem deseja entender a psicologia por trás das boas histórias, seja para escrever, seja para apreciar melhor as narrativas que consomem. Lisa Cron faz um excelente trabalho ao unir teoria e prática, oferecendo uma compreensão rica e completa de como começar uma história que vai realmente ressoar com o público. Ao mesmo tempo, o livro é uma reflexão profunda sobre a maneira como a ficção pode tocar o leitor e como as escolhas feitas no início de uma história podem determinar seu sucesso emocional.', 0, 5);




INSERT INTO RESENHAS  (res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao) VALUES 
(4,24,'O conto da aia
','"O Conto da Aia", escrito por Margaret Atwood, é uma obra distópica que, com uma narrativa poderosa e perturbadora, mergulha nas complexidades do poder, da opressão e da resistência em uma sociedade totalitária. Publicado em 1985, o romance se passa em Gilead, uma nação totalitária que surge após a queda dos Estados Unidos, onde as mulheres são subjugadas a um sistema de controle rigoroso que as reduz a funções específicas e limitadas. A protagonista, Defred, é uma das chamadas "aia", mulheres que são forçadas a ter filhos para a classe dominante, a fim de combater a infertilidade generalizada que aflige a sociedade. O livro aborda, de maneira incisiva, as consequências dessa opressão para a identidade, os direitos e as relações humanas.
A história é narrada pela própria Defred, uma mulher que, ao longo do romance, tenta se lembrar de sua vida anterior, quando era uma mulher livre, com família e trabalho. A narrativa se alterna entre o presente, com as experiências de Defred em Gilead, e flashes de seu passado, quando ela ainda era uma esposa e mãe, antes de sua vida ser completamente transformada pelo regime. A estrutura do romance é profundamente eficaz, pois, ao misturar memórias e acontecimentos atuais, Atwood constrói uma tensão constante que mantém o leitor imerso na jornada de Defred enquanto ela tenta encontrar um significado em sua existência, que é marcada pela violência e pela perda de sua identidade.
A sociedade de Gilead é regida por uma teocracia autoritária que utiliza a religião como uma justificativa para a opressão das mulheres. Em Gilead, as mulheres são divididas em castas rígidas: as esposas dos comandantes, as aias, as serviçais (chamadas de "mártires") e as "econoesposas", aquelas que são casadas com homens de classes mais baixas. As aias, como Defred, são usadas como reprodutoras em um regime onde o valor de uma mulher é reduzido à sua capacidade de gerar filhos. A gravidez e o parto, então, se tornam eventos de grande importância política, com as aias sendo forçadas a engravidar e dar à luz, enquanto suas crianças são levadas para os altos escalões do poder. O controle do corpo feminino é um dos principais e mais perturbadores aspectos dessa sociedade, e a narrativa de Atwood coloca o leitor diante da brutalidade dessa exploração.
O estilo de Atwood é ao mesmo tempo lírico e direto, criando um contraste entre a beleza de certas descrições e a violência implícita nas situações. A autora constrói uma atmosfera sufocante e claustrofóbica, na qual a luta pela sobrevivência se dá em meio a um constante estado de vigilância e repressão. Defred, embora seja uma mulher em um contexto de extrema subordinação, mantém um resquício de resistência interna, o que a torna uma personagem complexa e fascinante. Sua capacidade de refletir sobre o seu sofrimento, suas memórias e seus anseios por liberdade a transforma em uma voz poderosa, mesmo quando as opções externas para sua resistência são limitadas. A narrativa de Defred se caracteriza por momentos de amnésia e resignação, mas também por momentos de revolta silenciosa e tentativa de subversão.
A crítica social presente em "O Conto da Aia" é feroz e desafiadora, principalmente no que diz respeito à opressão das mulheres, à instrumentalização do corpo feminino e à manipulação da religião para justificar abusos de poder. Através de Gilead, Atwood reflete sobre como sistemas totalitários podem se aproveitar das vulnerabilidades de uma sociedade para impor suas próprias ideologias, e como o controle sobre a reprodução das mulheres pode ser uma forma de controle social. A autora não poupa os leitores de imagens gráficas e dolorosas da opressão, mas também revela as formas pelas quais as mulheres encontram maneiras de resistir e reivindicar sua agência, mesmo em um sistema que as desumaniza.
A relação entre Defred e os outros personagens também é uma parte central do livro. O comandante, seu “donos” de fato, representa a hipocrisia de uma elite que exerce poder sobre as mulheres, enquanto, ao mesmo tempo, é parte do sistema que as oprime. A relação entre Defred e a esposa do comandante, Serina Joy, é igualmente complexa. Embora Serina Joy seja uma mulher que, como Defred, sofre sob o regime, ela também compartilha do sistema que a submete. Essas relações são carregadas de tensão, inveja e uma luta silenciosa pela sobrevivência. O comandante, por sua vez, se apresenta como uma figura ambígua, ao mesmo tempo cúmplice do regime opressor e com sinais de uma humanidade complexa, que desafiam a visão simplista de vilão.
No final, "O Conto da Aia" deixa o leitor com uma sensação de inquietação e reflexão sobre o que significa liberdade, controle e resistência. Embora a narrativa de Defred seja uma jornada de sofrimento, o livro também sugere que, mesmo nas condições mais desesperadoras, a resistência pode existir em pequenas formas de subversão, nas palavras não ditas, nas memórias que se recusam a ser apagadas. O final do livro, aberto e ambíguo, provoca uma sensação de incerteza, mas também de esperança, sugerindo que, enquanto houver mulheres dispostas a desafiar os limites impostos sobre seus corpos e suas vidas, sempre haverá uma possibilidade de mudança.
Em resumo, "O Conto da Aia" é uma obra poderosa e perturbadora que não só captura a imaginação do leitor, mas também oferece uma reflexão sobre o poder, a liberdade e a opressão. Com uma narrativa complexa e personagens profundamente humanos, Margaret Atwood cria um mundo que, embora fictício, ressoa com as questões contemporâneas de controle social e de direitos das mulheres. O livro é um alerta, uma reflexão e, sobretudo, uma convocação à ação e à resistência contra qualquer forma de autoritarismo.', 0, 4);




INSERT INTO RESENHAS  (res_id, livro_id, resenha_titulo, resenha_texto, resenha_status, resenha_avaliacao) VALUES 
(4,26,'Como Treinar o Seu Dragão','"Como Treinar o Seu Dragão", escrito por Cressida Cowell, é o primeiro livro da famosa série infantojuvenil que mistura aventura, humor e fantasia de maneira envolvente e criativa. A obra transporta os leitores para o mundo dos vikings, onde dragões são parte do cotidiano e têm uma relação muito próxima com os habitantes das ilhas, mas de uma forma completamente diferente daquela que se poderia imaginar. A história é centrada em um jovem viking chamado Hiccup Horrendous Haddock III, que, ao contrário do que se espera de um herói de sua linhagem, é fraco, tímido e nada habilidoso em atividades que sua cultura viking tradicionalmente valoriza, como lutar e domar dragões.
O livro começa com Hiccup sendo desafiado a capturar e treinar um dragão, como parte de um ritual de passagem para os jovens vikings. Para a surpresa de todos, o dragão que Hiccup consegue capturar é um Fúria da Noite, uma espécie rara e temida que ninguém jamais conseguiu domesticar. Porém, ao contrário do que seu povo esperava, Hiccup não se sai como um herói de aventuras épicas. Ao invés de seguir o tradicional caminho de força bruta e ousadia, Hiccup, com sua inteligência e astúcia, tenta estabelecer uma conexão mais profunda e pacífica com o dragão, nomeando-o de Banguela. Essa relação entre Hiccup e seu dragão é o coração da história, pois mostra como a verdadeira força nem sempre está na batalha, mas sim na capacidade de compreender e estabelecer laços com os outros, seja com seres humanos ou criaturas fantásticas.
O enredo se desenrola em uma série de situações que misturam comédia e ação, com Hiccup se deparando com uma série de desafios e descobertas enquanto tenta provar a si mesmo e à sua tribo que há mais formas de ser um herói além da força física. A jornada de Hiccup é marcada pela superação de suas inseguranças e pela constante tentativa de encontrar seu lugar em um mundo onde as expectativas sobre o que significa ser um viking são altas e muito centradas em características como coragem e valentia. No entanto, ao longo do livro, ele começa a perceber que o verdadeiro valor vem de ser fiel a si mesmo, usando sua inteligência, compaixão e criatividade para resolver os problemas à sua frente.
Cressida Cowell constrói um mundo vibrante e único, onde os dragões não são apenas monstros a serem temidos, mas criaturas complexas, com personalidades próprias, que ajudam a enriquecer a história e a dar profundidade ao universo ficcional. A autora não se limita a criar uma narrativa simples de boas-vs-mal; ela questiona estereótipos e valores tradicionais, fazendo com que o leitor repense o conceito de heroísmo e liderança. Hiccup, com sua gentileza e inteligência, acaba mostrando ao longo da história que as melhores soluções nem sempre vêm das batalhas físicas, mas do entendimento e do trabalho em equipe.
O tom do livro é leve e humorado, com a autora fazendo uso de uma narrativa dinâmica, cheia de diálogos espirituosos e situações cômicas que tornam a leitura acessível e envolvente para crianças, mas também capaz de agradar aos adultos. O estilo de escrita de Cowell é descomplicado, com um toque de sarcasmo e ironia, o que cria uma atmosfera leve, mas também permite que o livro explore temas mais profundos, como amizade, aceitação e a busca pela identidade.
As ilustrações, também feitas pela autora, são outro ponto de destaque da obra. Elas não apenas complementam a narrativa, mas também ajudam a dar vida ao mundo dos dragões e dos vikings. O visual do livro possui um charme único, com esboços que capturam a essência das situações e dos personagens de maneira divertida, tornando a experiência de leitura ainda mais rica e envolvente.
"Como Treinar o Seu Dragão" é uma história sobre superação, a importância da empatia e o poder da inteligência em um mundo que muitas vezes valoriza a força bruta. A obra de Cressida Cowell, com seu equilíbrio entre ação, humor e reflexão, é uma excelente introdução ao mundo da fantasia, oferecendo lições valiosas de forma leve e acessível. Ao longo da história, o leitor é convidado a acompanhar Hiccup em sua jornada de amadurecimento e autodescoberta, aprendendo com ele que ser diferente e pensar de maneira única pode ser uma verdadeira força, algo que o torna uma figura heroica à sua própria maneira.', 0, 5);







