

INSERT INTO livros (livro_titulo, livro_sinopse, livro_editora, livro_isbn, livro_ano, livro_classidd, livro_foto)
VALUES 

('Harry Potter  e a Camara Secreta ','Depois de férias aborrecidas na casa dos tios trouxas, está na hora de Harry Potter voltar a estudar. Coisas acontecem, no entanto, para dificultar o regresso de Harry. Persistente e astuto, o herói não se deixa intimidar pelos obstáculos e, com a ajuda dos fiéis amigos Weasley, começa o ano letivo na Escola de Magia e Bruxaria de Hogwarts. As novidades não são poucas. Novos colegas, novos professores, muitas e boas descobertas e um grande e perigosos desafio. Alguém ou alguma coisa ameaça a segurança e a tranquilidade dos membros de Hogwarts.','Rocco',978-8532530790,2017-08-19
,'12+','.Harry Potter e a Câmara Secreta.jpg'),

('Harry Potter e o Prisioneiro de Azkaban','As aulas estão de volta à Hogwarts e Harry Potter não vê a hora de embarcar no expresso a vapor que o levará de volta à escola de bruxaria. Mais uma vez suas férias na rua dos Alfeneiros foi triste e solitária. Com muita ação, humor e magia, Harry Potter e o prisioneiro de Azkaban traz de volta o gigante atrapalhado Rúbeo Hagrid, o sábio diretor Alvo Dumbledore, a exigente professora de transformação Minerva MacGonagall e o novo mestre Lupin, que guarda grandes surpresas para Harry.','Rocco',978-8532530806,2017-08-19
,'12+','Harry Potter e o Prisioneiro de Azkaban.jpg'),

('Harry Potter  e o Calice de Fogo','Nesta aventura, o feiticeiro cresceu e está com 14 anos. O início do ano letivo de Harry Potter reserva muitas emoções, mágicas, e acontecimentos inesperados, além de um novo torneio em que os alunos de Hogwarts terão de demonstrar todas as habilidade mágicas e nãomágicas que vêm adquirindo ao longo de suas vidas. Harry é escolhido pelo Cálice de Fogo para competir como um dos campeões de Hogwarts, tendo ao lado seus fiéis amigos. Muitos desafios, feitiços, poções e confusões estão reservados para Harry. Além disso, ele terá que lidar ainda com os problemas comuns da adolescência amor, amizade, aceitação e rejeição.','Rocco',978-8532530813,2017-08-19
,'12+','Harry Potter e o Cálice de Fogo.jpg'),

('Harry Potter  e a Ordem da Fenix','Nesta aventura, o feiticeiro cresceu e está com 14 anos. O início do ano letivo de Harry Potter reserva muitas emoções, mágicas, e acontecimentos inesperados, além de um novo torneio em que os alunos de Hogwarts terão de demonstrar todas as habilidade mágicas e nãomágicas que vêm adquirindo ao longo de suas vidas. Harry é escolhido pelo Cálice de Fogo para competir como um dos campeões de Hogwarts, tendo ao lado seus fiéis amigos. Muitos desafios, feitiços, poções e confusões estão reservados para Harry. Além disso, ele terá que lidar ainda com os problemas comuns da adolescência amor, amizade, aceitação e rejeição.','Rocco',978-8532530820,2017-08-19
,'12+','Harry Potter e a Ordem da Fênix.jpg'),

('Harry Potter  e o Enigma do Principe','Harry Potter e o enigma do príncipe dá continuidade à saga do jovem bruxo Harry Potter a partir do ponto em que o livro anterior parou o momento em que fica provado que o poder de Voldemort e dos Comensais da Morte, seus seguidores, cresce mais a cada dia, em meio à batalha entre o bem e o mal. A onda de terror provocada pelo Lorde das Trevas estaria afetando, até mesmo, o mundo dos trouxas (nãobruxos), e sendo agravada pela ação dos dementadores, criaturas mágicas aterrorizantes que sugam a esperança e a felicidade das pessoas. Harry, que acabou de completar 16 anos, parte rumo ao sexto ano na Escola de Magia e Bruxaria de Hogwarts, animado e ao mesmo tempo apreensivo com a perspectiva de ter aulas particulares com o professor Dumbledore, o diretor da escola e o bruxo mais respeitado em toda comunidade mágica. Harry, longe de ser aquele menino magricela que vivia no quarto debaixo da escada na casa dos tios trouxas.','Rocco',978-8532530837,2017-08-19
,'12+','Harry Potter e o Enigma do Príncipe.jpg'),
 
('Harry Potter e as Relíquias da Morte' ,'Harry Potter  e as Relíquias da Morte, Harry Potter e as relíquias da morte, de J.K. Rowling, é o sétimo e último livro da série. Voldemorte está cada vez mais forte e Harry Potter precisa encontrar e aniquilar as Horcruxes para enfraquecer o lorde e poder enfrentálo. Nessa busca desenfreada, contando apenas com os amigos Rony e Hermione, Harry descobre as Relíquias da Morte, que serão úteis na batalha do bem contra o mal.','Rocco',978-8532530844,2017-08-19
,'12+','Harry Potter e as Relíquias da Morte.jpg'),

('O chamado selvagem','Buck é um cachorro enorme e afável que leva uma boa vida em um rancho na Califórnia, comendo e dormindo ao sol. Porém, durante a febre do ouro nos anos 1890, ele é sequestrado e vendido para trabalhar puxando trenós no gélido norte da América.
Passando por donos rudes e cruéis, Buck precisa lutar pela vida. À medida que aprende a se defender do porrete dos humanos e dos caninos de outros cães, ele cede a seus instintos primitivos, reconectando-se a seus antepassados.', 'Arqueiro' ,978-6555653151,2022-06-14,'12+','O chamado selvagem.jpg'),
 
('Caninos Brancos','Caninos brancos retrata a adaptabilidade social de uma criatura selvagem, o cachorro-lobo, e o seu progresso gradual para a civilização.','L&PM',978-8525411006
,2022-06-14,'12+','O chamado selvagem.jpg'),

('Diário de um Banana 1','Não é fácil ser criança. E ninguém sabe disso melhor do que Greg Heffley, que se vê mergulhado no mundo do ensino fundamental, onde fracotes são obrigados a dividir os corredores com garotos mais altos, mais malvados e que já se barbeiam. Em Diário de um Banana, o autor e ilustrados Jeff Kinney nos apresenta um herói improvável. Como Greg diz em seu diário. Só não espere que seja todo Querido Diário isso, Querido Diário aquilo. Para nossa sorte, o que Greg Heffley diz que fará e o que ele realmente faz são duas coisas bem diferentes.','VR Editora',978-8576831303
,2008-04-19,'10+','Diário de um Banana 1.jpg'),

('Viagem ao Centro da Terra','Quando o professor Lidenbrock encontrou um velho manuscrito islandês perdido em uma loja de livros usados em Hamburgo, imaginou que faria um mergulho profundo na crônica dos príncipes nórdicos da Idade Média. Perdido dentro do livro, porém, havia um bilhete de um cientista do século XVI que prometia a possibilidade de uma exploração a profundidades inimagináveis: em uma breve mensagem criptografada, Arne Saknussemm afirmava ter descoberto uma rota para o centro da Terra. Junto com seu sobrinho Axel e seu guia islandês Hans, o professor embarca em uma expedição secreta na qual, camada por camada, os primórdios da vida no planeta são revelados com a maestria e riqueza de detalhes características de Júlio Verne. ','L&PM',978-8576831303,2008-04-19,'10+','Viagem ao Centro da Terra.jpg'),


('O Homem Cão o senhor das Pulgas','Quando o oficial Rocha e seu cachorro Greg sofreram um acidente, o único jeito de os dois sobreviverem foi fundindo a cabeça do cão ao corpo do policial ― e foi assim que nasceu o Homem-Cão, o maior protetor da cidade! Desde então, nosso herói encontrou vários cãopanheiros: o Chefe, a poodle Zuzu, o robô Formigão e Pepezinho, um adorável gatinho.
Quando um novo grupo de caras malvados aparece na cidade, o Homem-Cão entra em ação ― e ele não está sozinho! Ao lado de Pepezinho e do Formigão, nosso Cãovaleiro das Trevas faz parte do grupo Superamigos, heróis sempre prontos para salvar todo mundo da cidade. Desta vez eles vão precisar unir forças a um aliado inesperado: o arqui-inimigo Pepê, o gato mais malvado do mundo. Mas será que ele é tão mau assim? Descubra a origem da vilania de Pepê e se ele finalmente vai deixar a amizade vencer pelo menos uma vez.','Companhia das Letrinhas',978-8574068824,2019-09-01,'livre','O Homem Cão o senhor das Pulgas  Vol. 5.jpg'),


('O livro da filosofia','Não é fácil ser criança. E ninguém sabe disso melhor do que Greg Heffley, que se vê mergulhado no mundo do ensino fundamental, onde fracotes são obrigados a dividir os corredores com garotos mais altos, mais malvados e que já se barbeiam. Em Diário de um Banana, o autor e ilustrados Jeff Kinney nos apresenta um herói improvável. Como Greg diz em seu diário. Só não espere que seja todo Querido Diário isso, Querido Diário aquilo. Para nossa sorte, o que Greg Heffley diz que fará e o que ele realmente faz são duas coisas bem diferentes.','Globo Livros',978-8525063090
,2016-10-06,'10+','O livro da filosofia.jpg');



INSERT INTO livros ( livro_titulo, livro_sinopse, livro_editora, livro_isbn, livro_ano, livro_classidd, livro_foto)
VALUES ('Alice no País das Maravilhas','Escrita em 1862, fruto da imaginação extraordinária de Lewis Carroll, esta obra transporta o leitor a uma viagem psicodélica e repleta de disparates. Tudo começa quando Alice se depara com um coelho branco que passa por ela correndo, apressado, e decide segui-lo até sua toca. A partir daí, um novo mundo se descortina diante dessa garotinha curiosa, que vai viver fantásticas aventuras repletas de acontecimentos absurdos ao lado de personagens excêntricos como o Chapeleiro Maluco, a Rainha de Copas, a Tartaruga Falsa e o Gato de Cheshire. Uma obra dinâmica, carregada de simbolismos e que, há mais de 150 anos, vem encantando leitores de todas as idades','Camelot Editora', '9786587817651', '2021','10+','alice.jpg');

INSERT INTO livros ( livro_titulo, livro_sinopse, livro_editora, livro_isbn, livro_ano, livro_classidd, livro_foto)
VALUES('Os sete maridos de Evelyn Hugo' ,'Lendária estrela de Hollywood, Evelyn Hugo sempre esteve sob os holofotes ― seja estrelando uma produção vencedora do Oscar, protagonizando algum escândalo ou aparecendo com um novo marido… pela sétima vez. Agora, prestes a completar oitenta anos e reclusa em seu apartamento no Upper East Side, a famigerada atriz decide contar a própria história ― ou sua (verdadeira história) ―, mas com uma condição: que Monique Grant, jornalista iniciante e até então desconhecida, seja a entrevistadora. Ao embarcar nessa misteriosa empreitada, a jovem repórter começa a se dar conta de que nada é por acaso ― e que suas trajetórias podem estar profunda e irreversivelmente conectadas.“Evelyn Hugo faz Elizabeth Taylor parecer sem graça. Você vai rir com ela, chorar, sofrer, e então voltar para a primeira página e fazer tudo de novo. ― Heather Cocks e Jessica Morgan, autoras de The Royal We','Paralela', '978-8584391509', '2019','+18 ','Os sete maridos de Evelyn Hugo.jpg');
 
 INSERT INTO livros ( livro_titulo, livro_sinopse, livro_editora, livro_isbn, livro_ano, livro_classidd, livro_foto)
VALUES('Quarta asa','Um dragão sem seu cavaleiro é uma tragédia. Um cavaleiro sem seu dragão é um homem morto. Em Quarta Asa, best-seller #1 do The New York Times, uma jovem precisa sobreviver ao treinamento em uma escola de elite para poderosos cavaleiros de dragões, onde a única regra é se formar... ou morrer tentando. Violet Sorrengail, uma jovem de vinte anos, estava destinada a entrar na Divisão dos Escribas, levando uma vida relativamente tranquila entre os livros e as aulas de História.','Planeta Minotauro','978-8542225853',2024, '16+','quartaasa.jpg');


INSERT INTO livros ( livro_titulo, livro_sinopse, livro_editora, livro_isbn, livro_ano, livro_classidd, livro_foto)
VALUES('O horizonte mora em um dia cinza', 'E se a superação da dor levar mais tempo que o esperado? Afinal, cada um tem seu próprio tempo de prantear. Ayla Vasconcellos está em meio ao processo de esperar que as feridas se tornem cicatrizes quando, inesperadamente, ocorre o esbarrão. Os óculos voando outra vez. Seria apenas coincidência o fato de Joon Hyuk, aquele coreano de olhos angulares e voz melodiosa, estar ali à sua frente, naquele exato segundo, numa universidade na Coreia do Sul? Ou algo mais profundo aguardava aqueles dois jovens que pertenciam a culturas tão distintas e que, no entanto, pareciam dividir as mesmas dores e as mesmas esperanças?', 'Mundo Cristão', '978-6559882991', 2024, '12+','horizontecinza.jpg');

INSERT INTO livros ( livro_titulo, livro_sinopse, livro_editora, livro_isbn, livro_ano, livro_classidd, livro_foto)
VALUES( 'Verity', 'Verity Crawford é a autora best-seller por trás de uma série de sucesso. Ela está no auge de sua carreira, aclamada pela crítica e pelo público, no entanto, um súbito e terrível acidente acaba interrompendo suas atividades, deixando-a sem condições de concluir a história... E é nessa complexa circunstância que surge Lowen Ashleigh, uma escritora à beira da falência convidada a escrever, sob um pseudônimo, os três livros restantes da já consolidada série. Para que consiga entender melhor o processo criativo de Verity com relação aos livros publicados e, ainda, tentar descobrir seus possíveis planos para os próximos, Lowen decide passar alguns dias na casa dos Crawford, imersa no caótico escritório de Verity - e, lá, encontra uma espécie de autobiografia onde a escritora narra os fatos acontecidos desde o dia em que conhece Jeremy, seu marido, até os instantes imediatamente anteriores a seu acidente - incluindo sua perspectiva sobre as tragédias ocorridas às filhas do casal. Quanto mais o tempo passa, mais Lowen se percebe envolvida em uma confusa rede de mentiras e segredos, e, lentamente, adquire sua própria posição no jogo psicológico que rodeia aquela casa. Emocional e fisicamente atraída por Jeremy, ela precisa decidir: expor uma versão que nem ele conhece sobre a própria esposa ou manter o sigilo dos escritos de Verity?', 'Galera', '978-8501117847',2020, '18+','verity.jpeg');


INSERT INTO livros ( livro_titulo, livro_sinopse, livro_editora, livro_isbn, livro_ano, livro_classidd, livro_foto)
VALUES('É assim que acaba','Lily nem sempre teve uma vida fácil, mas isso nunca a impediu de trabalhar arduamente para conquistar a vida tão sonhada. Ela percorreu um longo caminho desde a infância, em uma cidadezinha no Maine: se formou em marketing, se mudou para Boston e abriu a própria loja. Então, quando se sente atraída por um lindo neurocirurgião chamado Ryle Kincaid, tudo parece perfeito demais para ser verdade. Ryle é confiante, obstinado, quem sabe até um pouco arrogante. Mas também é sensível, brilhante e se sente atraído por Lily. Porém, sua grande aversão a relacionamentos é perturbadora. Mas quando Atlas, seu primeiro amor, reaparece de repente, Lily não consegue tirá-lo da cabeça , assim como a ligação com o passado que deixou para trás. E sobrecarregada com as questões sobre seu novo relacionamento, tudo que Lily construiu com Ryle fica em risco. Com um livro ousado e extremamente pessoal, Colleen Hoover conta uma história arrasadora, mas também inovadora. Uma narrativa inesquecível sobre um amor que custa caro demais. É assim que acaba trata de um assunto difícil com cuidado e um tremendo apanhado emocional. Os relacionamentos são retratados com honestidade e compaixão, e a nota da autora, que oferece um vislumbre da conexão pessoal de Hoover com a própria obra, é imperdível. Repleto de drama familiar e verdades dolorosas, este livro retrata de forma poderosa a devastação de relações abusivas e a força de seus sobreviventes.– Kirkus, Starred Review,', 'Galera', '978-6559812738',2023, '18+','assimqueacaba.jpeg')


INSERT INTO livros ( livro_titulo, livro_sinopse, livro_editora, livro_isbn, livro_ano, livro_classidd, livro_foto)
VALUES( 'É assim que começa', 'Lily Bloom continua administrado uma floricultura. Seu ex-marido abusivo, Ryle Kincaid, ainda é um cirurgião. Mas agora os dois estão oficialmente divorciados e dividem a guarda da filha, Emerson.
Quando Lily esbarra em Atlas ― com quem não fala há quase dois anos ―, é inegável que os dois podem retomar o relacionamento da adolescência, já que ele também está solteiro e parece corresponder seus sentimentos. Mas apesar de estar divorciada, Lily não está exatamente livre de Ryle. Culpando Atlas pelo fim de seu casamento, o ex-marido não está nada disposto a aceitar o novo relacionamento de Lily, principalmente no que diz respeito a Atlas, o último homem que aceitaria ver perto de sua filha e da ex-esposa.
Alternando entre as perspectivas de Altas e Lily, É assim que começa segue o epílogo do fenômeno editorial É assim que acaba . Revelando mais sobre o passado de Atlas e acompanhando Lily abraçar uma segunda chance no amor enquanto lida com um ex-marido ciumento, É assim que começa prova que ninguém entrega uma leitura mais emocionante do que Colleen Hoover.'
, 'Galera', '978-6559815067' ,2024,'18+','assimquecomeça.jpeg');

INSERT INTO livros ( livro_titulo, livro_sinopse, livro_editora, livro_isbn, livro_ano, livro_classidd, livro_foto)
VALUES( 'O conto da aia', 'O romance distópico O conto da aia, de Margaret Atwood, se passa num futuro muito próximo e tem como cenário uma república onde não existem mais jornais, revistas, livros nem filmes. As universidades foram extintas. Também já não há advogados, porque ninguém tem direito a defesa. Os cidadãos considerados criminosos são fuzilados e pendurados mortos no Muro, em praça pública, para servir de exemplo enquanto seus corpos apodrecem à vista de todos.', 'Rocco', '978-8532520661', 2017, '18+','contodaaia.jpeg');

INSERT INTO livros ( livro_titulo, livro_sinopse, livro_editora, livro_isbn, livro_ano, livro_classidd, livro_foto)
VALUES( 'Como treinar o seu dragão', 'Neste livro estão as memórias da época em que Soluço era apenas um garoto normal. Muito normal. Nem um pouco heroico. Ele precisava desesperadamente capturar e treinar um dragão, e teria de ser o animal mais impressionante de todos. Mas tudo o que conseguiu foi uma criaturinha pequena e banguela, nada ameaçadora. Foi então que seu destino de herói começou a ser traçado.
Inteiramente ilustrado, com muita ação e o tipo de humor que arranca gargalhadas até dos mais carrancudos, Como treinar o seu dragão é o primeiro livro de uma série que é sucesso mundial, escrita e ilustrada pela inglesa Cressida Cowell, autora premiada de obras infantis e infantojuvenis.
', 'Intrínseca', '978-8598078717',  2025, '10+','dragao.jpeg')

SELECT * FROM LIVROS
DELETE FROM LIVROS WHERE livro_id = 25

